DELETE FROM item;
DELETE FROM sqlite_sequence where name='item';
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Abacus', '', 1, 2, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Acid (vial)', 'As an action, you can splash the contents of this vial onto a creature within 5 feet of you or throw the vial up to 20 feet, shattering it on impact. In either case, make a ranged attack against a creature or object, treating the acid as an improvised weapon.  On a hit, the target takes 2d6 acid damage.', 1, 25, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Alchemist’s Fire (flask)', 'This sticky, adhesive fluid ignites when exposed to air. As an action, you can throw this flask up to 20 feet, shattering it on impact. Make a ranged attack against a creature or object, treating the alchemist’s fire as an improvised weapon. On a hit, the target takes 1d4 fire damage at the start of each of its turns. A creature can end this damage by using its action to make a DC 10 Dexterity check to extinguish the flames.', 1, 50, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (2, 'Arrows (20)', '', 1, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (2, 'Blowgun needles (50)', '', 1, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (2, 'Crossbow bolts (20)', '', 1, 1, 1.5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (2, 'Sling bullets (20)', '', 2, 4, 1.5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Antitoxin (vial)', 'A creature that drinks this vial of liquid gains advantage on saving throws against poison for 1 hour. It confers no benefit to undead or constructs.', 1, 50, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (3, 'Crystal', 'Specially constructed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use this as a spellcasting focus.', 1, 10, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (3, 'Orb', 'Specially constructed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use this as a spellcasting focus.', 1, 20, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (3, 'Rod','Specially constructed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use this as a spellcasting focus.', 1, 10, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (3, 'Staff', 'Specially constructed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use this as a spellcasting focus.', 1, 5, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (3, 'Wand', 'Specially constructed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use this as a spellcasting focus.', 1, 10, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Backpack', 'A backpack can hold up to 1 cubic foot or 30 pounds of gear. Additionally, you can also strap items, such a s a bedroll or a coil of rope, to the outside of a backpack.', 1, 2, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Ball Bearings', 'As an action, you can spill these tiny metal balls from their pouch to cover a level, square area that is 10 feet on a side. A creature moving across the covered area must succeed on a DC 10 Dexterity saving throw or fall prone. A creature moving through the area at half speed doesn’t need to make the save.', 1, 1, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Barrel', 'A barrel can hold up to 40 gallons of liquid, or 4 cubic feet of solid material.', 1, 2, 70, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Basket', 'A basket can hold up to 2 cubic feet, or 40 pounds of gear.', 3, 4, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Bedroll', '', 1, 1, 7, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Bell', '', 1, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Blanket', '', 3, 5, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Block and Tackle', 'A set of pulleys with a cable threaded through them and a hook to attach to objects, a block and tackle allows you to hoist up to four times the weight you can normally lift.', 1, 1, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Book', 'A book might contain poetry, historical accounts, information pertaining to a particular field of lore, diagrams and notes on gnomish contraptions, or just about anything else that can be represented using text or pictures. A book of spells is a spellbook (described later in this section).', 1, 25, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Bottle, glass', 'A bottle typically holds 1 1/2 pints of liquid.', 1, 2, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Box, alms', 'A small box containing donations. Holds up to 50 coins.', 1, 2, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Bucket', 'A bucket can hold up to 3 gallons of liquid, or a 1/2 cubic foot of solid material.', 2, 5, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Caltrops (bag of 20)', 'As an action, you can spread a bag of caltrops to cover a square area that is 5 feet on a side.  Any creature that enters the area must succeed on a DC 15 Dexterity saving throw or stop moving this turn and take 1 piercing damage. Taking this damage reduces the creature’s walking speed by 10 feet until the creature regains at least 1 hit point. A creature moving through the area at half speed doesn’t need to make the save.', 1, 1, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Candle', 'For 1 hour, a candle sheds bright light in a 5-­‐‑foot radius and dim light for an additional 5 feet.', 2, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Case, Crossbow Bolt', 'This wooden case can hold up to twenty crossbow bolts.', 1, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Case, Map or Scroll', 'This cylindrical leather case can hold up to ten rolled-­‐‑up sheets of paper or five rolled-­‐‑up sheets of parchment.', 1, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Censer', 'Incense is burned in this small metal bowl.', 1, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Chain (10 feet)', 'A chain has 10 hit points. It can be burst with a successful DC 20 Strength check.', 1, 5, 10, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Chalk (1 piece)', '', 2, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Chest', 'A chest holds 12 cubic feet, or 300 pounds of gear.', 1, 5, 25, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Climber’s Kit', 'A climber’s kit includes special pitons, boot tips, gloves, and a harness. You can use the climber’s kit as an action to anchor yourself; when you do, you can’t fall more than 25 feet from the point where you anchored yourself, and you can’t climb more than 25 feet away from that point without undoing the anchor.', 1, 25, 12, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Clothes, common', '', 1, 5, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Clothes, costume', '', 1, 5, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Clothes, fine', '', 1, 15, 6, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Clothes, traveler’s', '', 1, 2, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Clothes, vestments', '', 1, 15, 6, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Component Pouch', 'A component pouch is a small, watertight leather belt pouch that has compartments to hold all the material components and other special items you need to cast your spells, except for those components that have a specific cost (as indicated in a spell’s description).', 1, 25, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Crowbar', 'Using a crowbar grants advantage to Strength checks where the crowbar’s leverage can be applied.', 1, 2, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (5, 'Sprig of mistletoe', 'A special item through which druids channel the natural powers of the world. A druid can use such an object as a spellcasting focus.', 1, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (5, 'Totem', 'A special item through which druids channel the natural powers of the world. A druid can use such an object as a spellcasting focus.', 1, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (5, 'Wooden staff', 'A special item through which druids channel the natural powers of the world. A druid can use such an object as a spellcasting focus.', 1, 5, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (5, 'Yew wand', 'A special item through which druids channel the natural powers of the world. A druid can use such an object as a spellcasting focus.', 1, 10, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Fishing Tackle', 'This kit includes a wooden rod, silken line, corkwood bobbers, steel hooks, lead sinkers, velvet lures, and narrow netting.', 1, 1, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Flask', 'A flask holds up to 1 pint of liquid.', 2, 2, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Grappling hook', '', 1, 2, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Hammer', '', 1, 1, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Hammer, sledge', '', 1, 2, 10, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Healer’s Kit', 'This kit is a leather pouch containing bandages, salves, and splints. The kit has ten uses. As an action, you can expend one use of the kit to stabilize a creature that has 0 hit points, without needing to make a Wisdom (Medicine) check.', 1, 5, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (6, 'Amulet', 'A holy representation of a god or pantheon. A cleric or paladin can use it as a spellcasting focus. To use it in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield (as appropriate).', 1, 5, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (6, 'Emblem', 'A holy representation of a god or pantheon. A cleric or paladin can use it as a spellcasting focus. To use it in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield (as appropriate).', 1, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (6, 'Reliquary', 'A holy representation of a god or pantheon. A cleric or paladin can use it as a spellcasting focus. To use it in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield (as appropriate).', 1, 5, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Holy Water (flask)', 'As an action, you can splash the contents of this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact.  In either case, make a ranged attack against a target creature, treating the holy water as an improvised weapon. If the target is a fiend or undead, it takes 2d6 radiant damage.  A cleric or paladin may create holy water by performing a special ritual. The ritual takes 1 hour to perform, uses 25 gp worth of powdered silver, and requires the caster to expend a 1st-­‐‑level spell slot.', 1, 25, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Hourglass', '', 1, 25, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Hunting Trap', 'When you use your action to set it, this trap forms a saw-­‐‑toothed steel ring that snaps shut when a creature steps on a pressure plate in the center. The trap is affixed by a heavy chain to an immobile object, such as a tree or a spike driven into the ground. A creature that steps on the plate must succeed on a DC 13 Dexterity saving throw or take 1d4 piercing damage and stop moving. Thereafter, until the creature breaks free of the trap, its movement is limited by the length of the chain (typically 3 feet long). A creature can use its action to make a DC 13 Strength check, freeing itself or another creature within its reach on a success. Each failed check deals 1 piercing damage to the trapped creature.', 1, 5, 25, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Incense, block', 'A small brick of gum and spices which produces a sweet fragrance when burned.', 3, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Ink (1 ounce bottle)', '', 1, 10, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Ink pen', '', 2, 2, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Jug', 'A jug holds 1 gallon of liquid.', 2, 2, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Knife, small', 'Itsy bitsy teeny weeny full-tang letter slash machine-y.', 3, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Ladder (10-foot)', '', 3, 1, 25, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Lamp', 'A lamp casts bright light in a 15-­‐‑foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.', 2, 5, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Lantern, Bullseye', 'A bullseye lantern casts bright light in a 60-­‐‑foot cone and dim light for an additional 60 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.', 1, 10, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Lantern, Hooded', 'A hooded lantern casts bright light in a 30-­‐‑foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil. As an action, you can lower the hood, reducing the light to dim light in a 5-­‐‑foot radius.', 1, 5, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Lock', 'A key is provided with the lock. Without the key, a creature proficient with thieves’ tools can pick this lock with a successful DC 15 Dexterity check.  Your GM may decide that better locks are available for higher prices.', 1, 10, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Magnifying Glass', 'This lens allows a closer look at small objects. It is also useful as a substitute for flint and steel when starting fires. Lighting a fire with a magnifying glass requires light as bright as sunlight to focus, tinder to ignite, and about 5 minutes for the fire to ignite. A magnifying glass grants advantage on any ability check made to appraise or inspect an item that is small or highly detailed.', 1, 100, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Manacles', 'These metal restraints can bind a Small or Medium creature. Escaping the manacles requires a successful DC 20 Dexterity check. Breaking them requires a successful DC 20 Strength check. Each set of manacles comes with one key. Without the key, a creature proficient with thieves’ tools can pick the manacles’ lock with a successful DC 15 Dexterity check. Manacles have 15 hit points.', 1, 2, 6, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Mess Kit', 'This tin box contains a cup and simple cutlery. The box clamps together, and one side can be used as a cooking pan and the other as a plate or shallow bowl.', 3, 2, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Mirror, steel', '', 1, 5, 0.5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Oil (flask)', 'Oil usually comes in a clay flask that holds 1 pint. As an action, you can splash the oil in this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact. Make a ranged attack against a target creature or object, treating the oil as an improvised weapon. On a hit, the target is covered in oil. If the target takes any fire damage before the oil dries (after 1 minute), the target takes an additional 5 fire damage from the burning oil. You can also pour a flask of oil on the ground to cover a 5-­‐‑foot-­‐‑square area, provided that the surface is level.  If lit, the oil burns for 2 rounds and deals 5 fire damage to any creature that enters the area or ends its turn in the area. A creature can take this damage only once per turn.', 3, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Paper (one sheet)', '', 3, 2, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Parchment (one sheet)', '', 3, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Perfume (vial)', '', 1, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Pick, miner’s', '', 1, 2, 10, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Pitcher', 'A pitcher holds up to 1 gallon of liquid.', 2, 2, 4, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Piton', '', 2, 5, 0.25, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Poison, Basic (vial)', 'You can use the poison in this vial to coat one slashing or piercing weapon or up to three pieces of ammunition. Applying the poison takes an action. A creature hit by the poisoned weapon or ammunition must make a DC 10 Constitution saving throw or take 1d4 poison damage. Once applied, the poison retains potency for 1 minute before drying.', 1, 100, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Pot, iron', 'A pot can hold up to 1 gallon of liquid.', 1, 2, 10, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Potion of healing', 'A character who drinks the magical red fluid in this vial regains 2d4 + 2 hit points. Drinking or administering a potion takes an action.', 1, 50, 0.5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Pouch', 'A cloth or leather pouch can hold up to 20 sling bullets or 50 blowgun needles, among other things. A compartmentalized pouch for holding spell components is called a component pouch (described earlier in this section). A pouch can hold up to 1/5 cubic feet/30 pounds of gear.', 3, 5, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Quiver', 'A quiver can hold up to 20 arrows.', 1, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Ram, Portable', 'You can use a portable ram to break down doors. When doing so, you gain a +4 bonus on the Strength check. One other character can help you use the ram, giving you advantage on this check.', 1, 4, 35, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Rations (1 day)', 'Rations consist of dry foods suitable for extended travel, including jerky, dried fruit, hardtack, and nuts.', 3, 5, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Rope, hempen (50 feet)', 'Rope has 2 hit points and can be burst with a DC 17 Strength check.', 1, 1, 10, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Rope, silk (50 feet)', 'Rope has 2 hit points and can be burst with a DC 17 Strength check.', 1, 10, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Sand, small bag', 'A little bag of sand. What would you do with it?', 2, 1, 0.5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Sack', 'A sack holds 1 cubic foot, or 30 pounds of gear.', 2, 1, 0.5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Scale, Merchant’s', 'A scale includes a small balance, pans, and a suitable assortment of weights up to 2 pounds. With it, you can measure the exact weight of small objects, such as raw precious metals or trade goods, to help determine their worth.', 1, 5, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Sealing wax', '', 3, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Shovel', '', 1, 2, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Signal whistle', '', 2, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Signet ring', '', 1, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Soap', '', 2, 2, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Spellbook', 'Essential for wizards, a spellbook is a leather-­‐‑bound tome with 100 blank vellum pages suitable for recording spells.', 1, 50, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Spikes, iron (10)', '', 1, 1, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Spyglass', 'Objects viewed through a spyglass are magnified to twice their size.', 1, 1000, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'String, ball (10 feet)', '', 2, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Tankard', 'A tankard holds up to 1 pint of liquid.', 2, 2, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Tent, two-person', 'A simple and portable canvas shelter, a tent sleeps two.', 1, 2, 20, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Tinderbox', 'This small container holds flint, fire steel, and tinder (usually dry cloth soaked in light oil) used to kindle a fire. Using it to light a torch—or anything else with abundant, exposed fuel—takes an action. Lighting any other fire takes 1 minute.', 3, 5, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Torch', 'A torch burns for 1 hour, providing bright light in a 20-­‐‑foot radius and dim light for an additional 20 feet. If you make a melee attack with a burning torch and hit, it deals 1 fire damage.', 2, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Vial', 'A vial holds 4 ounces of liquid.', 1, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (4, 'Waterskin', 'A waterskin holds 4 pints of liquid.', 3, 2, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (1, 'Whetstone', '', 2, 1, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Alchemist’s supplies', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 50, 8, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Brewer’s supplies', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 20, 9, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Calligrapher’s supplies', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 10, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Carpenter’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 8, 6, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Cartographer’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 15, 6, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Cobbler’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 5, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Cook’s utensils', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 1, 8, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Glassblower’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 30, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Jeweler’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 25, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Leatherworker’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 5, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Mason’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 10, 8, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Painter’s supplies', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 10, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Potter’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 10, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Smith’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 20, 8, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Tinker’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 50, 10, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Weaver’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 1, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Woodcarver’s tools', 'These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan’s tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft.', 1, 1, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Disguise kit', 'This pouch of cosmetics, hair dye, and small props lets you create disguises that change your physical appearance. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to create a visual disguise.', 1, 25, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (7, 'Forgery kit', 'This small box contains a variety of papers and parchments, pens and inks, seals and sealing wax, gold and silver leaf, and other supplies necessary to create convincing forgeries of physical documents. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to create a physical forgery of a document.', 1, 15, 5, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (8, 'Dice set', 'If you are proficient with a gaming set, you can add your proficiency bonus to ability checks you make to play a game with that set.', 3, 1, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (8, 'Playing card set', 'If you are proficient with a gaming set, you can add your proficiency bonus to ability checks you make to play a game with that set.', 3, 5, 0, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Bagpipes', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 30, 6, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Drum', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 6, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Dulcimer', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 25, 10, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Flute', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 2, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Lute', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 35, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Lyre', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 30, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Horn', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 3, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Pan flute', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 12, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Shawm', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 2, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (9, 'Viol', 'If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument. A bard can use a musical instrument as a spellcasting focus.', 1, 30, 1, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (10, 'Herbalism kit', 'This kit contains a variety of instruments such as clippers, mortar and pestle, and pouches and vials used by herbalists to create remedies and potions. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to identify or apply herbs. Also, proficiency with this kit is required to create antitoxin and potions of healing.', 1, 5, 3, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (10, 'Navigator’s tools', 'This set of instruments is used for navigation at sea. Proficiency with navigator’s tools lets you chart a ship’s course and follow navigation charts. In addition, these tools allow you to add your proficiency bonus to any ability check you make to avoid getting lost at sea.', 1, 25, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (10, 'Poisoner’s kit', 'A poisoner’s kit includes the vials, chemicals, and other equipment necessary for the creation of poisons. Proficiency with this kit lets you add your proficiency bonus to any ability checks you make to craft or use poisons.', 1, 50, 2, NULL);
INSERT INTO item (itemType, name, description, coinID, cost, weight, bcUseAction) VALUES (10, 'Thieves’ tools', 'This set of tools includes a small file, a set of lock picks, a small mirror mounted on a metal handle, a set of narrow-­‐‑bladed scissors, and a pair of pliers. Proficiency with these tools lets you add your proficiency bonus to any ability checks you make to disarm traps or open locks.', 1, 25, 1 , NULL);

DELETE FROM itemType;
DELETE FROM sqlite_sequence where name='itemType';
INSERT INTO itemType (name) VALUES ('None');
INSERT INTO itemType (name) VALUES ('Ammunition');
INSERT INTO itemType (name) VALUES ('Arcane focus');
INSERT INTO itemType (name) VALUES ('Container');
INSERT INTO itemType (name) VALUES ('Druidic focus');
INSERT INTO itemType (name) VALUES ('Holy Symbol');
INSERT INTO itemType (name) VALUES ('Artisan’s tools');
INSERT INTO itemType (name) VALUES ('Gaming set');
INSERT INTO itemType (name) VALUES ('Musical instrument');
INSERT INTO itemType (name) VALUES ('Specialty tools');

DELETE FROM equipmentPack;
DELETE FROM sqlite_sequence where name='equipmentPack';
INSERT INTO equipmentPack (name, coinID, cost) VALUES ('Burglar’s Pack', 1, 16);
INSERT INTO equipmentPack (name, coinID, cost) VALUES ('Diplomat’s Pack', 1, 39);
INSERT INTO equipmentPack (name, coinID, cost) VALUES ('Dungeoneer’s Pack', 1, 12);
INSERT INTO equipmentPack (name, coinID, cost) VALUES ('Entertainer’s Pack', 1, 40);
INSERT INTO equipmentPack (name, coinID, cost) VALUES ('Explorer’s Pack', 1, 10);
INSERT INTO equipmentPack (name, coinID, cost) VALUES ('Priest’s Pack', 1, 19);
INSERT INTO equipmentPack (name, coinID, cost) VALUES ('Scholar’s Pack', 1, 40);

DELETE FROM packItem;
DELETE FROM sqlite_sequence where name='packItem';
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 14, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 15, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 99, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 19, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 27, 5);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 41, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 49, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 78, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 68, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 72, 2);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 85, 5);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 102, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 105, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (1, 86, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 33, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 29, 2);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 37, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 59, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 60, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 64, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 72, 2);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 73, 5);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 75, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 91, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (2, 95, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 14, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 41, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 49, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 78, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 103, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 102, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 85, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 105, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (3, 86, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (4, 14, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (4, 18, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (4, 36, 2);
INSERT INTO packItem (packID, itemID, quantity) VALUES (4, 27, 5);
INSERT INTO packItem (packID, itemID, quantity) VALUES (4, 85, 5);
INSERT INTO packItem (packID, itemID, quantity) VALUES (4, 105, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (4, 124, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 14, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 18, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 70, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 102, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 103, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 85, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 105, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (5, 86, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 14, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 20, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 27, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 102, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 24, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 58, 2);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 30, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 39, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 85, 2);
INSERT INTO packItem (packID, itemID, quantity) VALUES (6, 105, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (7, 14, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (7, 22, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (7, 59, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (7, 60, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (7, 74, 10);
INSERT INTO packItem (packID, itemID, quantity) VALUES (7, 88, 1);
INSERT INTO packItem (packID, itemID, quantity) VALUES (7, 62, 1);

