INSERT INTO fightingStyle (name, description) VALUES ('Archery', 'You gain a +2 bonus to attack rolls you make with ranged weapons.');
INSERT INTO fightingStyle (name, description) VALUES ('Defense', 'While you are wearing armor, you gain a +1 bonus to AC.');
INSERT INTO fightingStyle (name, description) VALUES ('Dueling', 'When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.');
INSERT INTO fightingStyle (name, description) VALUES ('Great Weapon Fighting', 'When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2. The weapon must have the two-­‐‑handed or versatile property for you to gain this benefit.');
INSERT INTO fightingStyle (name, description) VALUES ('Protection', 'When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll. You must be wielding a shield.');
INSERT INTO fightingStyle (name, description) VALUES ('Two-Weapon Fighting', 'When you engage in two-­‐‑weapon fighting, you can add your ability modifier to the damage of the second attack.');

INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (5, 1);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (5, 2);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (5, 3);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (5, 4);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (5, 5);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (5, 6);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (7, 2);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (7, 3);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (7, 4);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (7, 5);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (8, 1);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (8, 2);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (8, 3);
INSERT INTO classFightingStyle (classID, fightingStyleID) VALUES (8, 6);

INSERT INTO metamagicOption (name, description) VALUES ('Careful Spell', 'When you cast a spell that forces other creatures to make a saving throw, you can protect some of those creatures from the spell’s full force. To do so, you spend 1 sorcery point and choose a number of those creatures up to your Charisma modifier (minimum of one creature). A chosen creature automatically succeeds on its saving throw against the spell.');
INSERT INTO metamagicOption (name, description) VALUES ('Distant Spell', 'When you cast a spell that has a range of 5 feet or greater, you can spend 1 sorcery point to double the range of the spell.  When you cast a spell that has a range of touch, you can spend 1 sorcery point to make the range of the spell 30 feet.');
INSERT INTO metamagicOption (name, description) VALUES ('Empowered Spell', 'When you roll damage for a spell, you can spend 1 sorcery point to reroll a number of the damage dice up to your Charisma modifier (minimum of one).  You must use the new rolls.  You can use Empowered Spell even if you have already used a different Metamagic option during the casting of the spell.');
INSERT INTO metamagicOption (name, description) VALUES ('Extended Spell', 'When you cast a spell that has a duration of 1 minute or longer, you can spend 1 sorcery point to double its duration, to a maximum duration of 24 hours.');
INSERT INTO metamagicOption (name, description) VALUES ('Heightened Spell', 'When you cast a spell that forces a creature to make a saving throw to resist its effects, you can spend 3 sorcery points to give one target of the spell disadvantage on its first saving throw made against the spell.');
INSERT INTO metamagicOption (name, description) VALUES ('Quickened Spell', 'When you cast a spell that has a casting time of 1 action, you can spend 2 sorcery points to change the casting time to 1 bonus action for this casting.');
INSERT INTO metamagicOption (name, description) VALUES ('Subtle Spell', 'When you cast a spell, you can spend 1 sorcery point to cast it without any somatic or verbal components.');
INSERT INTO metamagicOption (name, description) VALUES ('Twinned Spell', 'When you cast a spell that targets only one creature and doesn’t have a range of self, you can spend a number of sorcery points equal to the spell’s level to target a second creature in range with the same spell (1 sorcery point if the spell is a cantrip).  To be eligible, a spell must be incapable of targeting more than one creature at the spell’s current level. For example, magic missile and scorching ray aren’t eligible, but ray of frost is.');

INSERT INTO pactBoon (name, description) VALUES ('Pact of the Chain', 'You learn the find familiar spell and can cast it as a ritual. The spell doesn’t count against your number of spells known.  When you cast the spell, you can choose one of the normal forms for your familiar or one of the following special forms: imp, pseudodragon, quasit, or sprite.  Additionally, when you take the Attack action, you can forgo one of your own attacks to allow your familiar to make one attack of its own with its reaction.');
INSERT INTO pactBoon (name, description) VALUES ('Pact of the Blade', 'You can use your action to create a pact weapon in your empty hand. You can choose the form that this melee weapon takes each time you create it. You are proficient with it while you wield it. This weapon counts as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.  Your pact weapon disappears if it is more than 5 feet away from you for 1 minute or more. It also disappears if you use this feature again, if you dismiss the weapon (no action required), or if you die.  You can transform one magic weapon into your pact weapon by performing a special ritual while you hold the weapon. You perform the ritual over the course of 1 hour, which can be done during a short rest. You can then dismiss the weapon, shunting it into an extradimensional space, and it appears whenever you create your pact weapon thereafter. You can’t affect an artifact or a sentient weapon in this way. The weapon ceases being your pact weapon if you die, if you perform the 1-­‐‑hour ritual on a different weapon, or if you use a 1-­‐‑hour ritual to break your bond to it. The weapon appears at your feet if it is in the extradimensional space when the bond breaks.');
INSERT INTO pactBoon (name, description) VALUES ('Pact of the Tome', 'Your patron gives you a grimoire called a Book of Shadows. When you gain this feature, choose three cantrips from any class’s spell list (the three needn’t be from the same list). While the book is on your person, you can cast those cantrips at will. They don’t count against your number of cantrips known.  If they don’t appear on the warlock spell list, they are nonetheless warlock spells for you.  If you lose your Book of Shadows, you can perform a 1-­‐‑hour ceremony to receive a replacement from your patron. This ceremony can be performed during a short or long rest, and it destroys the previous book. The book turns to ash when you die.');

INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Agonizing Blast', NULL, 'eldritch blast cantrip', 'When you cast eldritch blast, add your Charisma modifier to the damage it deals on a hit.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Armor of Shadows', NULL, NULL, 'You can cast mage armor on yourself at will, without expending a spell slot or material components.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Ascendant Step', 9, NULL, 'You can cast levitate on yourself at will, without expending a spell slot or material components.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Beast Speech', NULL, NULL, 'You can cast speak with animals at will, without expending a spell slot.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Beguiling Influence', NULL, NULL, 'You gain proficiency in the Deception and Persuasion skills.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Bewitching Whispers', 7, NULL, 'You can cast compulsion once using a warlock spell slot. You can’t do so again until you finish a long rest.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Book of Ancient Secrets', NULL, 'Pact of the Tome feature', 'You can now inscribe magical rituals in your Book of Shadows. Choose two 1st-­‐‑level spells that have the ritual tag from any class’s spell list (the two needn’t be from the same list). The spells appear in the book and don’t count against the number of spells you know. With your Book of Shadows in hand, you can cast the chosen spells as rituals. You can’t cast the spells except as rituals, unless you’ve learned them by some other means. You can also cast a warlock spell you know as a ritual if it has the ritual tag.  On your adventures, you can add other ritual spells to your Book of Shadows. When you find such a spell, you can add it to the book if the spell’s level is equal to or less than half your warlock level (rounded up) and if you can spare the time to transcribe the spell. For each level of the spell, the transcription process takes 2 hours and costs 50 gp for the rare inks needed to inscribe it.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Chains of Carceri', 15, 'Pact of the Chain feature', 'You can cast hold monster at will—targeting a celestial, fiend, or elemental—without expending a spell slot or material components. You must finish a long rest before you can use this invocation on the same creature again.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Devil’s Sight', NULL, NULL, 'You can see normally in darkness, both magical and nonmagical, to a distance of 120 feet.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Dreadful Word', 7, NULL, 'You can cast confusion once using a warlock spell slot. You can’t do so again until you finish a long rest.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Eldritch Sight', NULL, NULL, 'You can cast detect magic at will, without expending a spell slot.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Eldritch Spear', NULL, 'eldritch blast cantrip', 'When you cast eldritch blast, its range is 300 feet.  Eyes of the Rune Keeper You can read all writing.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Fiendish Vigor', NULL, NULL, 'You can cast false life on yourself at will as a 1st-­‐‑level spell, without expending a spell slot or material components.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Gaze of Two Minds', NULL, NULL, 'You can use your action to touch a willing humanoid and perceive through its senses until the end of your next turn. As long as the creature is on the same plane of existence as you, you can use your action on subsequent turns to maintain this connection, extending the duration until the end of your next turn. While perceiving through the other creature’s senses, you benefit from any special senses possessed by that creature, and you are blinded and deafened to your own surroundings.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Lifedrinker', 12, 'Pact of the Blade feature', 'When you hit a creature with your pact weapon, the creature takes extra necrotic damage equal to your Charisma modifier (minimum 1).');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Mask of Many Faces', NULL, NULL, 'You can cast disguise self at will, without expending a spell slot.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Master of Myriad Forms', 15, NULL, 'You can cast alter self at will, without expending a spell slot.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Minions of Chaos', 9, NULL, 'You can cast conjure elemental once using a warlock spell slot. You can’t do so again until you finish a long rest.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Mire the Mind', 5, NULL, 'You can cast slow once using a warlock spell slot.  You can’t do so again until you finish a long rest.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Misty Visions', NULL, NULL, 'You can cast silent image at will, without expending a spell slot or material components.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('One with Shadows', 5, NULL, 'When you are in an area of dim light or darkness, you can use your action to become invisible until you move or take an action or a reaction.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Otherworldly Leap', 9, NULL, 'You can cast jump on yourself at will, without expending a spell slot or material components.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Repelling Blast', NULL, 'eldritch blast cantrip', 'When you hit a creature with eldritch blast, you can push the creature up to 10 feet away from you in a straight line.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Sculptor of Flesh', 7, NULL, 'You can cast polymorph once using a warlock spell slot. You can’t do so again until you finish a long rest.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Sign of Ill Omen', 5, NULL, 'You can cast bestow curse once using a warlock spell slot. You can’t do so again until you finish a long rest.  Thief of Five Fates You can cast bane once using a warlock spell slot.  You can’t do so again until you finish a long rest.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Thirsting Blade', 5, 'Pact of the Blade feature', 'You can attack with your pact weapon twice, instead of once, whenever you take the Attack action on your turn.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Visions of Distant Realms', 15, NULL, 'You can cast arcane eye at will, without expending a spell slot.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Voice of the Chain Master', NULL, 'Pact of the Chain feature', 'You can communicate telepathically with your familiar and perceive through your familiar’s senses as long as you are on the same plane of existence.  Additionally, while perceiving through your familiar’s senses, you can also speak through your familiar in your own voice, even if your familiar is normally incapable of speech.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Whispers of the Grave', 9, NULL, 'You can cast speak with dead at will, without expending a spell slot.');
INSERT INTO warlockInvocation (name, levelPrereq, otherPrereq, description) VALUES ('Witch Sight', 15, NULL, 'You can see the true form of any shapechanger or creature concealed by illusion or transmutation magic while the creature is within 30 feet of you and within line of sight.');

INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (1, 2, 2);
INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (3, 3, 2);
INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (6, 4, 2);
INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (9, 4, 3);
INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (12, 5, 3);
INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (16, 5, 4);
INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (17, 6, 4);
INSERT INTO rageProgression (levelID, amount, damageBonus) VALUES (20, 999, 4);

INSERT INTO martialDamage (levelID, dieSize) VALUES (1, 4);
INSERT INTO martialDamage (levelID, dieSize) VALUES (5, 6);
INSERT INTO martialDamage (levelID, dieSize) VALUES (11, 8);
INSERT INTO martialDamage (levelID, dieSize) VALUES (17, 10);

INSERT INTO movementBonus (levelID, amount) VALUES (1, 0);
INSERT INTO movementBonus (levelID, amount) VALUES (2, 10);
INSERT INTO movementBonus (levelID, amount) VALUES (6, 15);
INSERT INTO movementBonus (levelID, amount) VALUES (10, 20);
INSERT INTO movementBonus (levelID, amount) VALUES (14, 25);
INSERT INTO movementBonus (levelID, amount) VALUES (18, 30);

INSERT INTO invocationsKnown (levelID, amount) VALUES (1, 0);
INSERT INTO invocationsKnown (levelID, amount) VALUES (2, 2);
INSERT INTO invocationsKnown (levelID, amount) VALUES (5, 3);
INSERT INTO invocationsKnown (levelID, amount) VALUES (7, 4);
INSERT INTO invocationsKnown (levelID, amount) VALUES (9, 5);
INSERT INTO invocationsKnown (levelID, amount) VALUES (12, 6);
INSERT INTO invocationsKnown (levelID, amount) VALUES (15, 7);
INSERT INTO invocationsKnown (levelID, amount) VALUES (18, 8);
