INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Barbarian', 12, 7, 0, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Bard', 8, 5, 3, 3);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Cleric', 8, 5, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Druid', 8, 5, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Fighter', 10, 6, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Monk', 8, 5, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Paladin', 10, 6, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Ranger', 10, 6, 3);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Rogue', 8, 5, 4);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Sorcerer', 6, 4, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Warlock', 8, 5, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Wizard', 6, 4, 2);

INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (2, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (2, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 4);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (6, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 4);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (9, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (9, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (10, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (11, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (11, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (12, 1);

INSERT INTO classWeaponPropProficiency (1, 1);
INSERT INTO classWeaponPropProficiency (1, 2);
INSERT INTO classWeaponPropProficiency (2, 1);
INSERT INTO classWeaponPropProficiency (3, 1);
INSERT INTO classWeaponPropProficiency (5, 1);
INSERT INTO classWeaponPropProficiency (5, 2);
INSERT INTO classWeaponPropProficiency (6, 1);
INSERT INTO classWeaponPropProficiency (7, 1);
INSERT INTO classWeaponPropProficiency (7, 2);
INSERT INTO classWeaponPropProficiency (8, 1);
INSERT INTO classWeaponPropProficiency (8, 2);
INSERT INTO classWeaponPropProficiency (9, 1);
INSERT INTO classWeaponPropProficiency (11, 1);

INSERT INTO classWeaponProficiency (2, 34);
INSERT INTO classWeaponProficiency (2, 22);
INSERT INTO classWeaponProficiency (2, 26);
INSERT INTO classWeaponProficiency (2, 28);
INSERT INTO classWeaponProficiency (4, 1);
INSERT INTO classWeaponProficiency (4, 2);
INSERT INTO classWeaponProficiency (4, 12);
INSERT INTO classWeaponProficiency (4, 5);
INSERT INTO classWeaponProficiency (4, 7);
INSERT INTO classWeaponProficiency (4, 8);
INSERT INTO classWeaponProficiency (4, 27);
INSERT INTO classWeaponProficiency (4, 9);
INSERT INTO classWeaponProficiency (4, 14);
INSERT INTO classWeaponProficiency (4, 10);
INSERT INTO classWeaponProficiency (6, 28);
INSERT INTO classWeaponProficiency (9, 34);
INSERT INTO classWeaponProficiency (9, 22);
INSERT INTO classWeaponProficiency (9, 26);
INSERT INTO classWeaponProficiency (9, 28);
INSERT INTO classWeaponProficiency (10, 2);
INSERT INTO classWeaponProficiency (10, 12);
INSERT INTO classWeaponProficiency (10, 14);
INSERT INTO classWeaponProficiency (10, 8);
INSERT INTO classWeaponProficiency (10, 11);
INSERT INTO classWeaponProficiency (12, 2);
INSERT INTO classWeaponProficiency (12, 12);
INSERT INTO classWeaponProficiency (12, 14);
INSERT INTO classWeaponProficiency (12, 8);
INSERT INTO classWeaponProficiency (12, 11);


