DELETE FROM startEquipTbl;
DELETE FROM sqlite_sequence where name='startEquipTbl';
INSERT INTO startEquipTbl (name) VALUES ('armor');
INSERT INTO startEquipTbl (name) VALUES ('item');
INSERT INTO startEquipTbl (name) VALUES ('itemType');
INSERT INTO startEquipTbl (name) VALUES ('weapon');
INSERT INTO startEquipTbl (name) VALUES ('weaponProperty');
INSERT INTO startEquipTbl (name) VALUES ('equipmentPack');

DELETE FROM startEquipItem;
DELETE FROM sqlite_sequence where name='startEquipItem';
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 5, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 5, 4);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 2, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 8, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 4, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 1, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 3, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 2, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 9, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 2, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 4, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 26, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 22, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 14, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 6, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 7, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 31, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 7, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 11, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 11, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 6, 20);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 6, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 5, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 27, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 36, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 4, 20);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 2, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 3, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 12, 10);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 28, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 5, 5);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 83, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 28, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 1, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 8, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 2, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 141, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 13, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 1, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 40, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 3, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 7, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 96, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 8, 1);

DELETE FROM startEquipBundle;
DELETE FROM sqlite_sequence where name='startEquipBundle';
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (1, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (2, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (3, 4, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (5, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (6, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (7, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (8, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (9, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (10, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (11, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (12, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (13, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (14, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (15, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (16, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (17, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (18, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (19, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (20, 21, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (22, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (23, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (24, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (4, 6, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (7, 25, 26);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (3, 14, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (27, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (28, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (29, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (30, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (31, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (25, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (32, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (26, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (33, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (34, 35, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (36, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (37, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (38, 32, 26);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (39, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (40, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (41, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (42, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (43, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (44, NULL, NULL);

DELETE FROM classBundleOption;
DELETE FROM sqlite_sequence where name='classBundleOption';
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 1, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 2, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 3, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 4, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 7, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 8, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 9, 10, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 11, 12, 5);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 13, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 14, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 15, 16, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 17, 6, 18);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 19, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 20, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 1, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 21, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 14, 6, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 22, 23, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 18, 24, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 25, 26, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 19, 4, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (6, 28, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (6, 29, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (6, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 18, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 14, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 25, 26, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 30, 23, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 20, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 31, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 32, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 33, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 17, 6, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 34, 35, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 36, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 37, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 11, 29, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 38, 29, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 39, 27, 1);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 36, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 19, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 40, 41, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 5, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 36, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 19, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 40, 41, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 42, 27, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 43, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 44, 7, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 40, 41, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 42, 1, NULL);

