INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Barbarian', 12, 7, 0, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Bard', 8, 5, 3, 3);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Cleric', 8, 5, 0, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Druid', 8, 5, 1, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Fighter', 10, 6, 0, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Monk', 8, 5, 1, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Paladin', 10, 6, 0, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Ranger', 10, 6, 0, 3);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Rogue', 8, 5, 1, 4);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Sorcerer', 6, 4, 0, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Warlock', 8, 5, 0, 2);
INSERT INTO class (name, hitDice, hpPerLevelAvg, numToolProfs, numSkills) VALUES ('Wizard', 6, 4, 0, 2);

INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (1, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (2, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (2, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (3, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (4, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 4);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (5, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (6, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 4);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (7, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 3);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (8, 5);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (9, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (9, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (10, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (11, 1);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (11, 2);
INSERT INTO classArmorProficiency (classID, armorTypeID) VALUES (12, 1);

INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (1, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (1, 2);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (2, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (3, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (5, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (5, 2);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (6, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (7, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (7, 2);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (8, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (8, 2);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (9, 1);
INSERT INTO classWeaponPropProficiency (classID, weaponPropertyID) VALUES (11, 1);

INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (2, 34);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (2, 22);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (2, 26);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (2, 28);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 1);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 2);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 12);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 5);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 7);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 8);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 27);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 9);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 14);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (4, 10);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (6, 28);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (9, 34);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (9, 22);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (9, 26);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (9, 28);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (10, 2);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (10, 12);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (10, 14);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (10, 8);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (10, 11);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (12, 2);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (12, 12);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (12, 14);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (12, 8);
INSERT INTO classWeaponProficiency (classID, weaponID) VALUES (12, 11);

INSERT INTO classToolTypeProficiency (classID, toolTypeID) VALUES (2, 9);
INSERT INTO classToolTypeProficiency (classID, toolTypeID) VALUES (6, 7);
INSERT INTO classToolTypeProficiency (classID, toolTypeID) VALUES (6, 9);

INSERT INTO classToolProficiency (classID, toolID) VALUES (4, 138);
INSERT INTO classToolProficiency (classID, toolID) VALUES (9, 141);

INSERT INTO classSavingThrow (classID, abilityID) VALUES (1, 1);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (1, 3);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (2, 2);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (2, 6);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (3, 5);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (3, 6);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (4, 4);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (4, 5);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (5, 1);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (5, 3);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (6, 1);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (6, 2);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (7, 5);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (7, 6);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (8, 1);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (8, 2);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (9, 2);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (9, 4);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (10, 3);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (10, 6);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (11, 5);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (11, 6);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (12, 4);
INSERT INTO classSavingThrow (classID, abilityID) VALUES (12, 5);

INSERT INTO classSkill (classID, skillID) VALUES (1, 11);
INSERT INTO classSkill (classID, skillID) VALUES (1, 2);
INSERT INTO classSkill (classID, skillID) VALUES (1, 17);
INSERT INTO classSkill (classID, skillID) VALUES (1, 9);
INSERT INTO classSkill (classID, skillID) VALUES (1, 14);
INSERT INTO classSkill (classID, skillID) VALUES (1, 15);
INSERT INTO classSkill (classID, skillID) VALUES (2, 1);
INSERT INTO classSkill (classID, skillID) VALUES (3, 7);
INSERT INTO classSkill (classID, skillID) VALUES (3, 12);
INSERT INTO classSkill (classID, skillID) VALUES (3, 13);
INSERT INTO classSkill (classID, skillID) VALUES (3, 19);
INSERT INTO classSkill (classID, skillID) VALUES (3, 10);
INSERT INTO classSkill (classID, skillID) VALUES (4, 6);
INSERT INTO classSkill (classID, skillID) VALUES (4, 11);
INSERT INTO classSkill (classID, skillID) VALUES (4, 12);
INSERT INTO classSkill (classID, skillID) VALUES (4, 13);
INSERT INTO classSkill (classID, skillID) VALUES (4, 9);
INSERT INTO classSkill (classID, skillID) VALUES (4, 14);
INSERT INTO classSkill (classID, skillID) VALUES (4, 10);
INSERT INTO classSkill (classID, skillID) VALUES (4, 15);
INSERT INTO classSkill (classID, skillID) VALUES (5, 3);
INSERT INTO classSkill (classID, skillID) VALUES (5, 11);
INSERT INTO classSkill (classID, skillID) VALUES (5, 2);
INSERT INTO classSkill (classID, skillID) VALUES (5, 7);
INSERT INTO classSkill (classID, skillID) VALUES (5, 12);
INSERT INTO classSkill (classID, skillID) VALUES (5, 17);
INSERT INTO classSkill (classID, skillID) VALUES (5, 14);
INSERT INTO classSkill (classID, skillID) VALUES (5, 15);
INSERT INTO classSkill (classID, skillID) VALUES (6, 3);
INSERT INTO classSkill (classID, skillID) VALUES (6, 2);
INSERT INTO classSkill (classID, skillID) VALUES (6, 7);
INSERT INTO classSkill (classID, skillID) VALUES (6, 12);
INSERT INTO classSkill (classID, skillID) VALUES (6, 10);
INSERT INTO classSkill (classID, skillID) VALUES (6, 5);
INSERT INTO classSkill (classID, skillID) VALUES (7, 2);
INSERT INTO classSkill (classID, skillID) VALUES (7, 12);
INSERT INTO classSkill (classID, skillID) VALUES (7, 17);
INSERT INTO classSkill (classID, skillID) VALUES (7, 13);
INSERT INTO classSkill (classID, skillID) VALUES (7, 19);
INSERT INTO classSkill (classID, skillID) VALUES (7, 10);
INSERT INTO classSkill (classID, skillID) VALUES (8, 11);
INSERT INTO classSkill (classID, skillID) VALUES (8, 2);
INSERT INTO classSkill (classID, skillID) VALUES (8, 12);
INSERT INTO classSkill (classID, skillID) VALUES (8, 8);
INSERT INTO classSkill (classID, skillID) VALUES (8, 9);
INSERT INTO classSkill (classID, skillID) VALUES (8, 14);
INSERT INTO classSkill (classID, skillID) VALUES (8, 5);
INSERT INTO classSkill (classID, skillID) VALUES (8, 15);
INSERT INTO classSkill (classID, skillID) VALUES (9, 3);
INSERT INTO classSkill (classID, skillID) VALUES (9, 2);
INSERT INTO classSkill (classID, skillID) VALUES (9, 16);
INSERT INTO classSkill (classID, skillID) VALUES (9, 12);
INSERT INTO classSkill (classID, skillID) VALUES (9, 17);
INSERT INTO classSkill (classID, skillID) VALUES (9, 8);
INSERT INTO classSkill (classID, skillID) VALUES (9, 14);
INSERT INTO classSkill (classID, skillID) VALUES (9, 18);
INSERT INTO classSkill (classID, skillID) VALUES (9, 19);
INSERT INTO classSkill (classID, skillID) VALUES (9, 4);
INSERT INTO classSkill (classID, skillID) VALUES (9, 5);
INSERT INTO classSkill (classID, skillID) VALUES (10, 6);
INSERT INTO classSkill (classID, skillID) VALUES (10, 16);
INSERT INTO classSkill (classID, skillID) VALUES (10, 12);
INSERT INTO classSkill (classID, skillID) VALUES (10, 17);
INSERT INTO classSkill (classID, skillID) VALUES (10, 19);
INSERT INTO classSkill (classID, skillID) VALUES (10, 10);
INSERT INTO classSkill (classID, skillID) VALUES (11, 6);
INSERT INTO classSkill (classID, skillID) VALUES (11, 16);
INSERT INTO classSkill (classID, skillID) VALUES (11, 7);
INSERT INTO classSkill (classID, skillID) VALUES (11, 17);
INSERT INTO classSkill (classID, skillID) VALUES (11, 8);
INSERT INTO classSkill (classID, skillID) VALUES (11, 9);
INSERT INTO classSkill (classID, skillID) VALUES (11, 10);
INSERT INTO classSkill (classID, skillID) VALUES (12, 6);
INSERT INTO classSkill (classID, skillID) VALUES (12, 7);
INSERT INTO classSkill (classID, skillID) VALUES (12, 12);
INSERT INTO classSkill (classID, skillID) VALUES (12, 8);
INSERT INTO classSkill (classID, skillID) VALUES (12, 13);
INSERT INTO classSkill (classID, skillID) VALUES (12, 10);

INSERT INTO startEquipTbl (name) VALUES ('armor');
INSERT INTO startEquipTbl (name) VALUES ('item');
INSERT INTO startEquipTbl (name) VALUES ('itemType');
INSERT INTO startEquipTbl (name) VALUES ('weapon');
INSERT INTO startEquipTbl (name) VALUES ('weaponProperty');
INSERT INTO startEquipTbl (name) VALUES ('equipmentPack');

INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 5, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 5, 4);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 2, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 8, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 4, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 1, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 3, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 2, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 9, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 2, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 4, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 26, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 22, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 14, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 6, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 7, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 31, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 7, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (1, 11, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 11, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 6, 20);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 6, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 5, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 27, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 36, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 4, 20);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 2, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 3, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 12, 10);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 28, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 5, 5);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 83, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 28, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 1, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (5, 8, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 2, 2);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 141, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 13, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (6, 1, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 40, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (3, 3, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 7, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (2, 96, 1);
INSERT INTO startEquipItem (tableID, itemID, quantity) VALUES (4, 8, 1);

INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (1, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (2, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (3, 4, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (5, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (6, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (7, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (8, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (9, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (10, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (11, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (12, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (13, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (14, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (15, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (16, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (17, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (18, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (19, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (20, 21, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (22, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (23, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (24, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (4, 6, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (7, 25, 26);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (3, 14, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (27, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (28, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (29, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (30, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (31, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (25, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (32, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (26, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (33, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (34, 35, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (36, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (37, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (38, 32, 26);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (39, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (40, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (41, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (42, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (43, NULL, NULL);
INSERT INTO startEquipBundle (item1ID, item2ID, item3ID) VALUES (44, NULL, NULL);

INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 1, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 2, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 3, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (1, 4, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 7, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 8, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 9, 10, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (2, 11, 12, 5);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 13, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 14, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 15, 16, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 17, 6, 18);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 19, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (3, 20, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 1, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 21, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 14, 6, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (4, 22, 23, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 18, 24, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 25, 26, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 19, 4, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (5, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (6, 28, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (6, 29, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (6, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 18, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 14, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 25, 26, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 30, 23, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (7, 20, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 31, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 32, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 33, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 17, 6, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 34, 35, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (8, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 36, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 37, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 11, 29, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 38, 29, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (9, 39, 27, 1);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 36, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 19, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 40, 41, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (10, 27, 1, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 6, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 5, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 36, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 19, 5, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 40, 41, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (11, 42, 27, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 43, NULL, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 44, 7, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 40, 41, NULL);
INSERT INTO classBundleOption (classID, bundle1ID, bundle2ID, bundle3ID) VALUES (12, 42, 1, NULL);
