DELETE FROM script;
DELETE FROM sqlite_sequence where name='script';
INSERT INTO script (name) VALUES ('None');
INSERT INTO script (name) VALUES ('Common');
INSERT INTO script (name) VALUES ('Dwarvish');
INSERT INTO script (name) VALUES ('Elvish');
INSERT INTO script (name) VALUES ('Infernal');
INSERT INTO script (name) VALUES ('Celestial');
INSERT INTO script (name) VALUES ('Draconic');

DELETE FROM language;
DELETE FROM sqlite_sequence where name='language';
INSERT INTO language (name, scriptID, exotic) VALUES ('Any', 1, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Common', 2, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Dwarvish', 3, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Elvish', 4, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Giant', 3, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Gnomish', 3, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Goblin', 3, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Halfling', 2, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Orc', 3, 0);
INSERT INTO language (name, scriptID, exotic) VALUES ('Abyssal', 5, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Celestial', 6, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Draconic', 7, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Deep Speech', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Infernal', 5, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Primordial', 3, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Primordial Auran', 3, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Primordial Aquan', 3, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Primordial Ignan', 3, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Primordial Terran', 3, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Sylvan', 4, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Undercommon', 4, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Gnoll', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Otyugh', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Sahuagin', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Sphinx', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Druidic', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Blink Dog', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Giant Eagle', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Giant Elk', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Giant Owl', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Winter Wolf', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Worg', 1, 1);
INSERT INTO language (name, scriptID, exotic) VALUES ('Thieves’ cant', 1, 1);
