INSERT INTO spellList (classID, spellID) VALUES (2, 71);
INSERT INTO spellList (classID, spellID) VALUES (2, 180);
INSERT INTO spellList (classID, spellID) VALUES (2, 187);
INSERT INTO spellList (classID, spellID) VALUES (2, 201);
INSERT INTO spellList (classID, spellID) VALUES (2, 202);
INSERT INTO spellList (classID, spellID) VALUES (2, 205);
INSERT INTO spellList (classID, spellID) VALUES (2, 227);
INSERT INTO spellList (classID, spellID) VALUES (2, 301);
INSERT INTO spellList (classID, spellID) VALUES (2, 304);
INSERT INTO spellList (classID, spellID) VALUES (2, 6);
INSERT INTO spellList (classID, spellID) VALUES (2, 22);
INSERT INTO spellList (classID, spellID) VALUES (2, 39);
INSERT INTO spellList (classID, spellID) VALUES (2, 49);
INSERT INTO spellList (classID, spellID) VALUES (2, 70);
INSERT INTO spellList (classID, spellID) VALUES (2, 79);
INSERT INTO spellList (classID, spellID) VALUES (2, 83);
INSERT INTO spellList (classID, spellID) VALUES (2, 105);
INSERT INTO spellList (classID, spellID) VALUES (2, 109);
INSERT INTO spellList (classID, spellID) VALUES (2, 154);
INSERT INTO spellList (classID, spellID) VALUES (2, 158);
INSERT INTO spellList (classID, spellID) VALUES (2, 159);
INSERT INTO spellList (classID, spellID) VALUES (2, 166);
INSERT INTO spellList (classID, spellID) VALUES (2, 167);
INSERT INTO spellList (classID, spellID) VALUES (2, 185);
INSERT INTO spellList (classID, spellID) VALUES (2, 266);
INSERT INTO spellList (classID, spellID) VALUES (2, 268);
INSERT INTO spellList (classID, spellID) VALUES (2, 272);
INSERT INTO spellList (classID, spellID) VALUES (2, 292);
INSERT INTO spellList (classID, spellID) VALUES (2, 302);
INSERT INTO spellList (classID, spellID) VALUES (2, 7);
INSERT INTO spellList (classID, spellID) VALUES (2, 31);
INSERT INTO spellList (classID, spellID) VALUES (2, 37);
INSERT INTO spellList (classID, spellID) VALUES (2, 81);
INSERT INTO spellList (classID, spellID) VALUES (2, 97);
INSERT INTO spellList (classID, spellID) VALUES (2, 100);
INSERT INTO spellList (classID, spellID) VALUES (2, 155);
INSERT INTO spellList (classID, spellID) VALUES (2, 161);
INSERT INTO spellList (classID, spellID) VALUES (2, 173);
INSERT INTO spellList (classID, spellID) VALUES (2, 176);
INSERT INTO spellList (classID, spellID) VALUES (2, 178);
INSERT INTO spellList (classID, spellID) VALUES (2, 182);
INSERT INTO spellList (classID, spellID) VALUES (2, 184);
INSERT INTO spellList (classID, spellID) VALUES (2, 191);
INSERT INTO spellList (classID, spellID) VALUES (2, 255);
INSERT INTO spellList (classID, spellID) VALUES (2, 260);
INSERT INTO spellList (classID, spellID) VALUES (2, 265);
INSERT INTO spellList (classID, spellID) VALUES (2, 283);
INSERT INTO spellList (classID, spellID) VALUES (2, 319);
INSERT INTO spellList (classID, spellID) VALUES (2, 26);
INSERT INTO spellList (classID, spellID) VALUES (2, 42);
INSERT INTO spellList (classID, spellID) VALUES (2, 86);
INSERT INTO spellList (classID, spellID) VALUES (2, 108);
INSERT INTO spellList (classID, spellID) VALUES (2, 139);
INSERT INTO spellList (classID, spellID) VALUES (2, 164);
INSERT INTO spellList (classID, spellID) VALUES (2, 194);
INSERT INTO spellList (classID, spellID) VALUES (2, 213);
INSERT INTO spellList (classID, spellID) VALUES (2, 221);
INSERT INTO spellList (classID, spellID) VALUES (2, 257);
INSERT INTO spellList (classID, spellID) VALUES (2, 273);
INSERT INTO spellList (classID, spellID) VALUES (2, 274);
INSERT INTO spellList (classID, spellID) VALUES (2, 279);
INSERT INTO spellList (classID, spellID) VALUES (2, 294);
INSERT INTO spellList (classID, spellID) VALUES (2, 295);
INSERT INTO spellList (classID, spellID) VALUES (2, 50);
INSERT INTO spellList (classID, spellID) VALUES (2, 52);
INSERT INTO spellList (classID, spellID) VALUES (2, 82);
INSERT INTO spellList (classID, spellID) VALUES (2, 130);
INSERT INTO spellList (classID, spellID) VALUES (2, 142);
INSERT INTO spellList (classID, spellID) VALUES (2, 150);
INSERT INTO spellList (classID, spellID) VALUES (2, 183);
INSERT INTO spellList (classID, spellID) VALUES (2, 223);
INSERT INTO spellList (classID, spellID) VALUES (2, 10);
INSERT INTO spellList (classID, spellID) VALUES (2, 21);
INSERT INTO spellList (classID, spellID) VALUES (2, 92);
INSERT INTO spellList (classID, spellID) VALUES (2, 93);
INSERT INTO spellList (classID, spellID) VALUES (2, 134);
INSERT INTO spellList (classID, spellID) VALUES (2, 143);
INSERT INTO spellList (classID, spellID) VALUES (2, 160);
INSERT INTO spellList (classID, spellID) VALUES (2, 177);
INSERT INTO spellList (classID, spellID) VALUES (2, 195);
INSERT INTO spellList (classID, spellID) VALUES (2, 208);
INSERT INTO spellList (classID, spellID) VALUES (2, 210);
INSERT INTO spellList (classID, spellID) VALUES (2, 219);
INSERT INTO spellList (classID, spellID) VALUES (2, 238);
INSERT INTO spellList (classID, spellID) VALUES (2, 253);
INSERT INTO spellList (classID, spellID) VALUES (2, 256);
INSERT INTO spellList (classID, spellID) VALUES (2, 290);
INSERT INTO spellList (classID, spellID) VALUES (2, 103);
INSERT INTO spellList (classID, spellID) VALUES (2, 113);
INSERT INTO spellList (classID, spellID) VALUES (2, 145);
INSERT INTO spellList (classID, spellID) VALUES (2, 174);
INSERT INTO spellList (classID, spellID) VALUES (2, 198);
INSERT INTO spellList (classID, spellID) VALUES (2, 232);
INSERT INTO spellList (classID, spellID) VALUES (2, 300);
INSERT INTO spellList (classID, spellID) VALUES (2, 17);
INSERT INTO spellList (classID, spellID) VALUES (2, 101);
INSERT INTO spellList (classID, spellID) VALUES (2, 128);
INSERT INTO spellList (classID, spellID) VALUES (2, 193);
INSERT INTO spellList (classID, spellID) VALUES (2, 206);
INSERT INTO spellList (classID, spellID) VALUES (2, 233);
INSERT INTO spellList (classID, spellID) VALUES (2, 241);
INSERT INTO spellList (classID, spellID) VALUES (2, 246);
INSERT INTO spellList (classID, spellID) VALUES (2, 286);
INSERT INTO spellList (classID, spellID) VALUES (2, 289);
INSERT INTO spellList (classID, spellID) VALUES (2, 91);
INSERT INTO spellList (classID, spellID) VALUES (2, 110);
INSERT INTO spellList (classID, spellID) VALUES (2, 137);
INSERT INTO spellList (classID, spellID) VALUES (2, 204);
INSERT INTO spellList (classID, spellID) VALUES (2, 225);
INSERT INTO spellList (classID, spellID) VALUES (2, 129);
INSERT INTO spellList (classID, spellID) VALUES (2, 224);
INSERT INTO spellList (classID, spellID) VALUES (2, 298);
INSERT INTO spellList (classID, spellID) VALUES (3, 146);
INSERT INTO spellList (classID, spellID) VALUES (3, 180);
INSERT INTO spellList (classID, spellID) VALUES (3, 201);
INSERT INTO spellList (classID, spellID) VALUES (3, 245);
INSERT INTO spellList (classID, spellID) VALUES (3, 250);
INSERT INTO spellList (classID, spellID) VALUES (3, 271);
INSERT INTO spellList (classID, spellID) VALUES (3, 291);
INSERT INTO spellList (classID, spellID) VALUES (3, 22);
INSERT INTO spellList (classID, spellID) VALUES (3, 29);
INSERT INTO spellList (classID, spellID) VALUES (3, 46);
INSERT INTO spellList (classID, spellID) VALUES (3, 67);
INSERT INTO spellList (classID, spellID) VALUES (3, 70);
INSERT INTO spellList (classID, spellID) VALUES (3, 78);
INSERT INTO spellList (classID, spellID) VALUES (3, 79);
INSERT INTO spellList (classID, spellID) VALUES (3, 80);
INSERT INTO spellList (classID, spellID) VALUES (3, 147);
INSERT INTO spellList (classID, spellID) VALUES (3, 154);
INSERT INTO spellList (classID, spellID) VALUES (3, 170);
INSERT INTO spellList (classID, spellID) VALUES (3, 235);
INSERT INTO spellList (classID, spellID) VALUES (3, 237);
INSERT INTO spellList (classID, spellID) VALUES (3, 251);
INSERT INTO spellList (classID, spellID) VALUES (3, 262);
INSERT INTO spellList (classID, spellID) VALUES (3, 3);
INSERT INTO spellList (classID, spellID) VALUES (3, 20);
INSERT INTO spellList (classID, spellID) VALUES (3, 31);
INSERT INTO spellList (classID, spellID) VALUES (3, 37);
INSERT INTO spellList (classID, spellID) VALUES (3, 62);
INSERT INTO spellList (classID, spellID) VALUES (3, 97);
INSERT INTO spellList (classID, spellID) VALUES (3, 114);
INSERT INTO spellList (classID, spellID) VALUES (3, 135);
INSERT INTO spellList (classID, spellID) VALUES (3, 161);
INSERT INTO spellList (classID, spellID) VALUES (3, 178);
INSERT INTO spellList (classID, spellID) VALUES (3, 184);
INSERT INTO spellList (classID, spellID) VALUES (3, 226);
INSERT INTO spellList (classID, spellID) VALUES (3, 236);
INSERT INTO spellList (classID, spellID) VALUES (3, 265);
INSERT INTO spellList (classID, spellID) VALUES (3, 278);
INSERT INTO spellList (classID, spellID) VALUES (3, 310);
INSERT INTO spellList (classID, spellID) VALUES (3, 319);
INSERT INTO spellList (classID, spellID) VALUES (3, 9);
INSERT INTO spellList (classID, spellID) VALUES (3, 25);
INSERT INTO spellList (classID, spellID) VALUES (3, 26);
INSERT INTO spellList (classID, spellID) VALUES (3, 42);
INSERT INTO spellList (classID, spellID) VALUES (3, 66);
INSERT INTO spellList (classID, spellID) VALUES (3, 74);
INSERT INTO spellList (classID, spellID) VALUES (3, 86);
INSERT INTO spellList (classID, spellID) VALUES (3, 139);
INSERT INTO spellList (classID, spellID) VALUES (3, 188);
INSERT INTO spellList (classID, spellID) VALUES (3, 197);
INSERT INTO spellList (classID, spellID) VALUES (3, 200);
INSERT INTO spellList (classID, spellID) VALUES (3, 234);
INSERT INTO spellList (classID, spellID) VALUES (3, 243);
INSERT INTO spellList (classID, spellID) VALUES (3, 248);
INSERT INTO spellList (classID, spellID) VALUES (3, 257);
INSERT INTO spellList (classID, spellID) VALUES (3, 273);
INSERT INTO spellList (classID, spellID) VALUES (3, 277);
INSERT INTO spellList (classID, spellID) VALUES (3, 295);
INSERT INTO spellList (classID, spellID) VALUES (3, 312);
INSERT INTO spellList (classID, spellID) VALUES (3, 23);
INSERT INTO spellList (classID, spellID) VALUES (3, 63);
INSERT INTO spellList (classID, spellID) VALUES (3, 75);
INSERT INTO spellList (classID, spellID) VALUES (3, 87);
INSERT INTO spellList (classID, spellID) VALUES (3, 130);
INSERT INTO spellList (classID, spellID) VALUES (3, 144);
INSERT INTO spellList (classID, spellID) VALUES (3, 183);
INSERT INTO spellList (classID, spellID) VALUES (3, 280);
INSERT INTO spellList (classID, spellID) VALUES (3, 47);
INSERT INTO spellList (classID, spellID) VALUES (3, 60);
INSERT INTO spellList (classID, spellID) VALUES (3, 85);
INSERT INTO spellList (classID, spellID) VALUES (3, 121);
INSERT INTO spellList (classID, spellID) VALUES (3, 134);
INSERT INTO spellList (classID, spellID) VALUES (3, 143);
INSERT INTO spellList (classID, spellID) VALUES (3, 149);
INSERT INTO spellList (classID, spellID) VALUES (3, 171);
INSERT INTO spellList (classID, spellID) VALUES (3, 177);
INSERT INTO spellList (classID, spellID) VALUES (3, 195);
INSERT INTO spellList (classID, spellID) VALUES (3, 219);
INSERT INTO spellList (classID, spellID) VALUES (3, 238);
INSERT INTO spellList (classID, spellID) VALUES (3, 253);
INSERT INTO spellList (classID, spellID) VALUES (3, 28);
INSERT INTO spellList (classID, spellID) VALUES (3, 68);
INSERT INTO spellList (classID, spellID) VALUES (3, 113);
INSERT INTO spellList (classID, spellID) VALUES (3, 127);
INSERT INTO spellList (classID, spellID) VALUES (3, 151);
INSERT INTO spellList (classID, spellID) VALUES (3, 153);
INSERT INTO spellList (classID, spellID) VALUES (3, 157);
INSERT INTO spellList (classID, spellID) VALUES (3, 218);
INSERT INTO spellList (classID, spellID) VALUES (3, 300);
INSERT INTO spellList (classID, spellID) VALUES (3, 318);
INSERT INTO spellList (classID, spellID) VALUES (3, 54);
INSERT INTO spellList (classID, spellID) VALUES (3, 89);
INSERT INTO spellList (classID, spellID) VALUES (3, 101);
INSERT INTO spellList (classID, spellID) VALUES (3, 119);
INSERT INTO spellList (classID, spellID) VALUES (3, 220);
INSERT INTO spellList (classID, spellID) VALUES (3, 241);
INSERT INTO spellList (classID, spellID) VALUES (3, 246);
INSERT INTO spellList (classID, spellID) VALUES (3, 286);
INSERT INTO spellList (classID, spellID) VALUES (3, 12);
INSERT INTO spellList (classID, spellID) VALUES (3, 64);
INSERT INTO spellList (classID, spellID) VALUES (3, 95);
INSERT INTO spellList (classID, spellID) VALUES (3, 162);
INSERT INTO spellList (classID, spellID) VALUES (3, 19);
INSERT INTO spellList (classID, spellID) VALUES (3, 133);
INSERT INTO spellList (classID, spellID) VALUES (3, 196);
INSERT INTO spellList (classID, spellID) VALUES (3, 299);
INSERT INTO spellList (classID, spellID) VALUES (4, 94);
INSERT INTO spellList (classID, spellID) VALUES (4, 146);
INSERT INTO spellList (classID, spellID) VALUES (4, 201);
INSERT INTO spellList (classID, spellID) VALUES (4, 222);
INSERT INTO spellList (classID, spellID) VALUES (4, 231);
INSERT INTO spellList (classID, spellID) VALUES (4, 245);
INSERT INTO spellList (classID, spellID) VALUES (4, 263);
INSERT INTO spellList (classID, spellID) VALUES (4, 6);
INSERT INTO spellList (classID, spellID) VALUES (4, 39);
INSERT INTO spellList (classID, spellID) VALUES (4, 67);
INSERT INTO spellList (classID, spellID) VALUES (4, 70);
INSERT INTO spellList (classID, spellID) VALUES (4, 79);
INSERT INTO spellList (classID, spellID) VALUES (4, 80);
INSERT INTO spellList (classID, spellID) VALUES (4, 99);
INSERT INTO spellList (classID, spellID) VALUES (4, 105);
INSERT INTO spellList (classID, spellID) VALUES (4, 126);
INSERT INTO spellList (classID, spellID) VALUES (4, 140);
INSERT INTO spellList (classID, spellID) VALUES (4, 154);
INSERT INTO spellList (classID, spellID) VALUES (4, 175);
INSERT INTO spellList (classID, spellID) VALUES (4, 185);
INSERT INTO spellList (classID, spellID) VALUES (4, 237);
INSERT INTO spellList (classID, spellID) VALUES (4, 272);
INSERT INTO spellList (classID, spellID) VALUES (4, 292);
INSERT INTO spellList (classID, spellID) VALUES (4, 7);
INSERT INTO spellList (classID, spellID) VALUES (4, 24);
INSERT INTO spellList (classID, spellID) VALUES (4, 73);
INSERT INTO spellList (classID, spellID) VALUES (4, 97);
INSERT INTO spellList (classID, spellID) VALUES (4, 114);
INSERT INTO spellList (classID, spellID) VALUES (4, 120);
INSERT INTO spellList (classID, spellID) VALUES (4, 122);
INSERT INTO spellList (classID, spellID) VALUES (4, 148);
INSERT INTO spellList (classID, spellID) VALUES (4, 155);
INSERT INTO spellList (classID, spellID) VALUES (4, 161);
INSERT INTO spellList (classID, spellID) VALUES (4, 178);
INSERT INTO spellList (classID, spellID) VALUES (4, 182);
INSERT INTO spellList (classID, spellID) VALUES (4, 184);
INSERT INTO spellList (classID, spellID) VALUES (4, 211);
INSERT INTO spellList (classID, spellID) VALUES (4, 214);
INSERT INTO spellList (classID, spellID) VALUES (4, 236);
INSERT INTO spellList (classID, spellID) VALUES (4, 276);
INSERT INTO spellList (classID, spellID) VALUES (4, 36);
INSERT INTO spellList (classID, spellID) VALUES (4, 53);
INSERT INTO spellList (classID, spellID) VALUES (4, 74);
INSERT INTO spellList (classID, spellID) VALUES (4, 86);
INSERT INTO spellList (classID, spellID) VALUES (4, 200);
INSERT INTO spellList (classID, spellID) VALUES (4, 221);
INSERT INTO spellList (classID, spellID) VALUES (4, 234);
INSERT INTO spellList (classID, spellID) VALUES (4, 269);
INSERT INTO spellList (classID, spellID) VALUES (4, 274);
INSERT INTO spellList (classID, spellID) VALUES (4, 311);
INSERT INTO spellList (classID, spellID) VALUES (4, 312);
INSERT INTO spellList (classID, spellID) VALUES (4, 316);
INSERT INTO spellList (classID, spellID) VALUES (4, 30);
INSERT INTO spellList (classID, spellID) VALUES (4, 52);
INSERT INTO spellList (classID, spellID) VALUES (4, 57);
INSERT INTO spellList (classID, spellID) VALUES (4, 58);
INSERT INTO spellList (classID, spellID) VALUES (4, 63);
INSERT INTO spellList (classID, spellID) VALUES (4, 90);
INSERT INTO spellList (classID, spellID) VALUES (4, 130);
INSERT INTO spellList (classID, spellID) VALUES (4, 136);
INSERT INTO spellList (classID, spellID) VALUES (4, 150);
INSERT INTO spellList (classID, spellID) VALUES (4, 165);
INSERT INTO spellList (classID, spellID) VALUES (4, 183);
INSERT INTO spellList (classID, spellID) VALUES (4, 223);
INSERT INTO spellList (classID, spellID) VALUES (4, 280);
INSERT INTO spellList (classID, spellID) VALUES (4, 281);
INSERT INTO spellList (classID, spellID) VALUES (4, 305);
INSERT INTO spellList (classID, spellID) VALUES (4, 11);
INSERT INTO spellList (classID, spellID) VALUES (4, 21);
INSERT INTO spellList (classID, spellID) VALUES (4, 48);
INSERT INTO spellList (classID, spellID) VALUES (4, 55);
INSERT INTO spellList (classID, spellID) VALUES (4, 60);
INSERT INTO spellList (classID, spellID) VALUES (4, 134);
INSERT INTO spellList (classID, spellID) VALUES (4, 143);
INSERT INTO spellList (classID, spellID) VALUES (4, 171);
INSERT INTO spellList (classID, spellID) VALUES (4, 195);
INSERT INTO spellList (classID, spellID) VALUES (4, 219);
INSERT INTO spellList (classID, spellID) VALUES (4, 242);
INSERT INTO spellList (classID, spellID) VALUES (4, 253);
INSERT INTO spellList (classID, spellID) VALUES (4, 297);
INSERT INTO spellList (classID, spellID) VALUES (4, 308);
INSERT INTO spellList (classID, spellID) VALUES (4, 56);
INSERT INTO spellList (classID, spellID) VALUES (4, 113);
INSERT INTO spellList (classID, spellID) VALUES (4, 153);
INSERT INTO spellList (classID, spellID) VALUES (4, 157);
INSERT INTO spellList (classID, spellID) VALUES (4, 212);
INSERT INTO spellList (classID, spellID) VALUES (4, 284);
INSERT INTO spellList (classID, spellID) VALUES (4, 296);
INSERT INTO spellList (classID, spellID) VALUES (4, 309);
INSERT INTO spellList (classID, spellID) VALUES (4, 315);
INSERT INTO spellList (classID, spellID) VALUES (4, 119);
INSERT INTO spellList (classID, spellID) VALUES (4, 206);
INSERT INTO spellList (classID, spellID) VALUES (4, 220);
INSERT INTO spellList (classID, spellID) VALUES (4, 241);
INSERT INTO spellList (classID, spellID) VALUES (4, 247);
INSERT INTO spellList (classID, spellID) VALUES (4, 8);
INSERT INTO spellList (classID, spellID) VALUES (4, 13);
INSERT INTO spellList (classID, spellID) VALUES (4, 64);
INSERT INTO spellList (classID, spellID) VALUES (4, 95);
INSERT INTO spellList (classID, spellID) VALUES (4, 110);
INSERT INTO spellList (classID, spellID) VALUES (4, 285);
INSERT INTO spellList (classID, spellID) VALUES (4, 129);
INSERT INTO spellList (classID, spellID) VALUES (4, 259);
INSERT INTO spellList (classID, spellID) VALUES (4, 282);
INSERT INTO spellList (classID, spellID) VALUES (4, 299);
INSERT INTO spellList (classID, spellID) VALUES (7, 29);
INSERT INTO spellList (classID, spellID) VALUES (7, 46);
INSERT INTO spellList (classID, spellID) VALUES (7, 70);
INSERT INTO spellList (classID, spellID) VALUES (7, 78);
INSERT INTO spellList (classID, spellID) VALUES (7, 79);
INSERT INTO spellList (classID, spellID) VALUES (7, 80);
INSERT INTO spellList (classID, spellID) VALUES (7, 88);
INSERT INTO spellList (classID, spellID) VALUES (7, 158);
INSERT INTO spellList (classID, spellID) VALUES (7, 235);
INSERT INTO spellList (classID, spellID) VALUES (7, 237);
INSERT INTO spellList (classID, spellID) VALUES (7, 262);
INSERT INTO spellList (classID, spellID) VALUES (7, 3);
INSERT INTO spellList (classID, spellID) VALUES (7, 34);
INSERT INTO spellList (classID, spellID) VALUES (7, 112);
INSERT INTO spellList (classID, spellID) VALUES (7, 178);
INSERT INTO spellList (classID, spellID) VALUES (7, 184);
INSERT INTO spellList (classID, spellID) VALUES (7, 192);
INSERT INTO spellList (classID, spellID) VALUES (7, 236);
INSERT INTO spellList (classID, spellID) VALUES (7, 319);
INSERT INTO spellList (classID, spellID) VALUES (7, 66);
INSERT INTO spellList (classID, spellID) VALUES (7, 74);
INSERT INTO spellList (classID, spellID) VALUES (7, 86);
INSERT INTO spellList (classID, spellID) VALUES (7, 188);
INSERT INTO spellList (classID, spellID) VALUES (7, 243);
INSERT INTO spellList (classID, spellID) VALUES (7, 248);
INSERT INTO spellList (classID, spellID) VALUES (7, 23);
INSERT INTO spellList (classID, spellID) VALUES (7, 75);
INSERT INTO spellList (classID, spellID) VALUES (7, 183);
INSERT INTO spellList (classID, spellID) VALUES (7, 85);
INSERT INTO spellList (classID, spellID) VALUES (7, 134);
INSERT INTO spellList (classID, spellID) VALUES (7, 238);
INSERT INTO spellList (classID, spellID) VALUES (8, 4);
INSERT INTO spellList (classID, spellID) VALUES (8, 6);
INSERT INTO spellList (classID, spellID) VALUES (8, 70);
INSERT INTO spellList (classID, spellID) VALUES (8, 79);
INSERT INTO spellList (classID, spellID) VALUES (8, 80);
INSERT INTO spellList (classID, spellID) VALUES (8, 126);
INSERT INTO spellList (classID, spellID) VALUES (8, 140);
INSERT INTO spellList (classID, spellID) VALUES (8, 163);
INSERT INTO spellList (classID, spellID) VALUES (8, 175);
INSERT INTO spellList (classID, spellID) VALUES (8, 185);
INSERT INTO spellList (classID, spellID) VALUES (8, 272);
INSERT INTO spellList (classID, spellID) VALUES (8, 7);
INSERT INTO spellList (classID, spellID) VALUES (8, 24);
INSERT INTO spellList (classID, spellID) VALUES (8, 73);
INSERT INTO spellList (classID, spellID) VALUES (8, 114);
INSERT INTO spellList (classID, spellID) VALUES (8, 178);
INSERT INTO spellList (classID, spellID) VALUES (8, 182);
INSERT INTO spellList (classID, spellID) VALUES (8, 184);
INSERT INTO spellList (classID, spellID) VALUES (8, 214);
INSERT INTO spellList (classID, spellID) VALUES (8, 236);
INSERT INTO spellList (classID, spellID) VALUES (8, 265);
INSERT INTO spellList (classID, spellID) VALUES (8, 276);
INSERT INTO spellList (classID, spellID) VALUES (8, 53);
INSERT INTO spellList (classID, spellID) VALUES (8, 74);
INSERT INTO spellList (classID, spellID) VALUES (8, 213);
INSERT INTO spellList (classID, spellID) VALUES (8, 221);
INSERT INTO spellList (classID, spellID) VALUES (8, 234);
INSERT INTO spellList (classID, spellID) VALUES (8, 274);
INSERT INTO spellList (classID, spellID) VALUES (8, 311);
INSERT INTO spellList (classID, spellID) VALUES (8, 312);
INSERT INTO spellList (classID, spellID) VALUES (8, 316);
INSERT INTO spellList (classID, spellID) VALUES (8, 58);
INSERT INTO spellList (classID, spellID) VALUES (8, 130);
INSERT INTO spellList (classID, spellID) VALUES (8, 183);
INSERT INTO spellList (classID, spellID) VALUES (8, 281);
INSERT INTO spellList (classID, spellID) VALUES (8, 48);
INSERT INTO spellList (classID, spellID) VALUES (8, 297);
INSERT INTO spellList (classID, spellID) VALUES (10, 2);
INSERT INTO spellList (classID, spellID) VALUES (10, 40);
INSERT INTO spellList (classID, spellID) VALUES (10, 71);
INSERT INTO spellList (classID, spellID) VALUES (10, 117);
INSERT INTO spellList (classID, spellID) VALUES (10, 180);
INSERT INTO spellList (classID, spellID) VALUES (10, 187);
INSERT INTO spellList (classID, spellID) VALUES (10, 201);
INSERT INTO spellList (classID, spellID) VALUES (10, 202);
INSERT INTO spellList (classID, spellID) VALUES (10, 205);
INSERT INTO spellList (classID, spellID) VALUES (10, 222);
INSERT INTO spellList (classID, spellID) VALUES (10, 227);
INSERT INTO spellList (classID, spellID) VALUES (10, 240);
INSERT INTO spellList (classID, spellID) VALUES (10, 264);
INSERT INTO spellList (classID, spellID) VALUES (10, 301);
INSERT INTO spellList (classID, spellID) VALUES (10, 35);
INSERT INTO spellList (classID, spellID) VALUES (10, 39);
INSERT INTO spellList (classID, spellID) VALUES (10, 45);
INSERT INTO spellList (classID, spellID) VALUES (10, 49);
INSERT INTO spellList (classID, spellID) VALUES (10, 79);
INSERT INTO spellList (classID, spellID) VALUES (10, 83);
INSERT INTO spellList (classID, spellID) VALUES (10, 102);
INSERT INTO spellList (classID, spellID) VALUES (10, 107);
INSERT INTO spellList (classID, spellID) VALUES (10, 109);
INSERT INTO spellList (classID, spellID) VALUES (10, 126);
INSERT INTO spellList (classID, spellID) VALUES (10, 175);
INSERT INTO spellList (classID, spellID) VALUES (10, 186);
INSERT INTO spellList (classID, spellID) VALUES (10, 190);
INSERT INTO spellList (classID, spellID) VALUES (10, 261);
INSERT INTO spellList (classID, spellID) VALUES (10, 266);
INSERT INTO spellList (classID, spellID) VALUES (10, 268);
INSERT INTO spellList (classID, spellID) VALUES (10, 292);
INSERT INTO spellList (classID, spellID) VALUES (10, 5);
INSERT INTO spellList (classID, spellID) VALUES (10, 31);
INSERT INTO spellList (classID, spellID) VALUES (10, 33);
INSERT INTO spellList (classID, spellID) VALUES (10, 72);
INSERT INTO spellList (classID, spellID) VALUES (10, 73);
INSERT INTO spellList (classID, spellID) VALUES (10, 81);
INSERT INTO spellList (classID, spellID) VALUES (10, 97);
INSERT INTO spellList (classID, spellID) VALUES (10, 98);
INSERT INTO spellList (classID, spellID) VALUES (10, 148);
INSERT INTO spellList (classID, spellID) VALUES (10, 161);
INSERT INTO spellList (classID, spellID) VALUES (10, 173);
INSERT INTO spellList (classID, spellID) VALUES (10, 176);
INSERT INTO spellList (classID, spellID) VALUES (10, 179);
INSERT INTO spellList (classID, spellID) VALUES (10, 207);
INSERT INTO spellList (classID, spellID) VALUES (10, 209);
INSERT INTO spellList (classID, spellID) VALUES (10, 252);
INSERT INTO spellList (classID, spellID) VALUES (10, 255);
INSERT INTO spellList (classID, spellID) VALUES (10, 260);
INSERT INTO spellList (classID, spellID) VALUES (10, 275);
INSERT INTO spellList (classID, spellID) VALUES (10, 283);
INSERT INTO spellList (classID, spellID) VALUES (10, 313);
INSERT INTO spellList (classID, spellID) VALUES (10, 32);
INSERT INTO spellList (classID, spellID) VALUES (10, 42);
INSERT INTO spellList (classID, spellID) VALUES (10, 65);
INSERT INTO spellList (classID, spellID) VALUES (10, 74);
INSERT INTO spellList (classID, spellID) VALUES (10, 86);
INSERT INTO spellList (classID, spellID) VALUES (10, 108);
INSERT INTO spellList (classID, spellID) VALUES (10, 116);
INSERT INTO spellList (classID, spellID) VALUES (10, 125);
INSERT INTO spellList (classID, spellID) VALUES (10, 132);
INSERT INTO spellList (classID, spellID) VALUES (10, 152);
INSERT INTO spellList (classID, spellID) VALUES (10, 164);
INSERT INTO spellList (classID, spellID) VALUES (10, 181);
INSERT INTO spellList (classID, spellID) VALUES (10, 194);
INSERT INTO spellList (classID, spellID) VALUES (10, 234);
INSERT INTO spellList (classID, spellID) VALUES (10, 269);
INSERT INTO spellList (classID, spellID) VALUES (10, 270);
INSERT INTO spellList (classID, spellID) VALUES (10, 279);
INSERT INTO spellList (classID, spellID) VALUES (10, 295);
INSERT INTO spellList (classID, spellID) VALUES (10, 311);
INSERT INTO spellList (classID, spellID) VALUES (10, 312);
INSERT INTO spellList (classID, spellID) VALUES (10, 23);
INSERT INTO spellList (classID, spellID) VALUES (10, 30);
INSERT INTO spellList (classID, spellID) VALUES (10, 52);
INSERT INTO spellList (classID, spellID) VALUES (10, 82);
INSERT INTO spellList (classID, spellID) VALUES (10, 90);
INSERT INTO spellList (classID, spellID) VALUES (10, 142);
INSERT INTO spellList (classID, spellID) VALUES (10, 165);
INSERT INTO spellList (classID, spellID) VALUES (10, 223);
INSERT INTO spellList (classID, spellID) VALUES (10, 281);
INSERT INTO spellList (classID, spellID) VALUES (10, 305);
INSERT INTO spellList (classID, spellID) VALUES (10, 10);
INSERT INTO spellList (classID, spellID) VALUES (10, 44);
INSERT INTO spellList (classID, spellID) VALUES (10, 51);
INSERT INTO spellList (classID, spellID) VALUES (10, 69);
INSERT INTO spellList (classID, spellID) VALUES (10, 92);
INSERT INTO spellList (classID, spellID) VALUES (10, 160);
INSERT INTO spellList (classID, spellID) VALUES (10, 171);
INSERT INTO spellList (classID, spellID) VALUES (10, 256);
INSERT INTO spellList (classID, spellID) VALUES (10, 287);
INSERT INTO spellList (classID, spellID) VALUES (10, 290);
INSERT INTO spellList (classID, spellID) VALUES (10, 308);
INSERT INTO spellList (classID, spellID) VALUES (10, 38);
INSERT INTO spellList (classID, spellID) VALUES (10, 41);
INSERT INTO spellList (classID, spellID) VALUES (10, 84);
INSERT INTO spellList (classID, spellID) VALUES (10, 103);
INSERT INTO spellList (classID, spellID) VALUES (10, 138);
INSERT INTO spellList (classID, spellID) VALUES (10, 198);
INSERT INTO spellList (classID, spellID) VALUES (10, 212);
INSERT INTO spellList (classID, spellID) VALUES (10, 284);
INSERT INTO spellList (classID, spellID) VALUES (10, 300);
INSERT INTO spellList (classID, spellID) VALUES (10, 76);
INSERT INTO spellList (classID, spellID) VALUES (10, 101);
INSERT INTO spellList (classID, spellID) VALUES (10, 115);
INSERT INTO spellList (classID, spellID) VALUES (10, 119);
INSERT INTO spellList (classID, spellID) VALUES (10, 220);
INSERT INTO spellList (classID, spellID) VALUES (10, 228);
INSERT INTO spellList (classID, spellID) VALUES (10, 247);
INSERT INTO spellList (classID, spellID) VALUES (10, 289);
INSERT INTO spellList (classID, spellID) VALUES (10, 91);
INSERT INTO spellList (classID, spellID) VALUES (10, 95);
INSERT INTO spellList (classID, spellID) VALUES (10, 169);
INSERT INTO spellList (classID, spellID) VALUES (10, 225);
INSERT INTO spellList (classID, spellID) VALUES (10, 285);
INSERT INTO spellList (classID, spellID) VALUES (10, 133);
INSERT INTO spellList (classID, spellID) VALUES (10, 203);
INSERT INTO spellList (classID, spellID) VALUES (10, 224);
INSERT INTO spellList (classID, spellID) VALUES (10, 293);
INSERT INTO spellList (classID, spellID) VALUES (10, 317);
INSERT INTO spellList (classID, spellID) VALUES (11, 40);
INSERT INTO spellList (classID, spellID) VALUES (11, 96);
INSERT INTO spellList (classID, spellID) VALUES (11, 187);
INSERT INTO spellList (classID, spellID) VALUES (11, 205);
INSERT INTO spellList (classID, spellID) VALUES (11, 222);
INSERT INTO spellList (classID, spellID) VALUES (11, 227);
INSERT INTO spellList (classID, spellID) VALUES (11, 301);
INSERT INTO spellList (classID, spellID) VALUES (11, 39);
INSERT INTO spellList (classID, spellID) VALUES (11, 49);
INSERT INTO spellList (classID, spellID) VALUES (11, 102);
INSERT INTO spellList (classID, spellID) VALUES (11, 156);
INSERT INTO spellList (classID, spellID) VALUES (11, 167);
INSERT INTO spellList (classID, spellID) VALUES (11, 235);
INSERT INTO spellList (classID, spellID) VALUES (11, 302);
INSERT INTO spellList (classID, spellID) VALUES (11, 72);
INSERT INTO spellList (classID, spellID) VALUES (11, 100);
INSERT INTO spellList (classID, spellID) VALUES (11, 161);
INSERT INTO spellList (classID, spellID) VALUES (11, 173);
INSERT INTO spellList (classID, spellID) VALUES (11, 207);
INSERT INTO spellList (classID, spellID) VALUES (11, 209);
INSERT INTO spellList (classID, spellID) VALUES (11, 239);
INSERT INTO spellList (classID, spellID) VALUES (11, 260);
INSERT INTO spellList (classID, spellID) VALUES (11, 275);
INSERT INTO spellList (classID, spellID) VALUES (11, 283);
INSERT INTO spellList (classID, spellID) VALUES (11, 65);
INSERT INTO spellList (classID, spellID) VALUES (11, 86);
INSERT INTO spellList (classID, spellID) VALUES (11, 108);
INSERT INTO spellList (classID, spellID) VALUES (11, 125);
INSERT INTO spellList (classID, spellID) VALUES (11, 132);
INSERT INTO spellList (classID, spellID) VALUES (11, 164);
INSERT INTO spellList (classID, spellID) VALUES (11, 188);
INSERT INTO spellList (classID, spellID) VALUES (11, 194);
INSERT INTO spellList (classID, spellID) VALUES (11, 243);
INSERT INTO spellList (classID, spellID) VALUES (11, 295);
INSERT INTO spellList (classID, spellID) VALUES (11, 303);
INSERT INTO spellList (classID, spellID) VALUES (11, 23);
INSERT INTO spellList (classID, spellID) VALUES (11, 30);
INSERT INTO spellList (classID, spellID) VALUES (11, 82);
INSERT INTO spellList (classID, spellID) VALUES (11, 150);
INSERT INTO spellList (classID, spellID) VALUES (11, 59);
INSERT INTO spellList (classID, spellID) VALUES (11, 93);
INSERT INTO spellList (classID, spellID) VALUES (11, 160);
INSERT INTO spellList (classID, spellID) VALUES (11, 253);
INSERT INTO spellList (classID, spellID) VALUES (11, 41);
INSERT INTO spellList (classID, spellID) VALUES (11, 56);
INSERT INTO spellList (classID, spellID) VALUES (11, 68);
INSERT INTO spellList (classID, spellID) VALUES (11, 103);
INSERT INTO spellList (classID, spellID) VALUES (11, 123);
INSERT INTO spellList (classID, spellID) VALUES (11, 198);
INSERT INTO spellList (classID, spellID) VALUES (11, 300);
INSERT INTO spellList (classID, spellID) VALUES (11, 101);
INSERT INTO spellList (classID, spellID) VALUES (11, 115);
INSERT INTO spellList (classID, spellID) VALUES (11, 128);
INSERT INTO spellList (classID, spellID) VALUES (11, 220);
INSERT INTO spellList (classID, spellID) VALUES (11, 77);
INSERT INTO spellList (classID, spellID) VALUES (11, 91);
INSERT INTO spellList (classID, spellID) VALUES (11, 110);
INSERT INTO spellList (classID, spellID) VALUES (11, 137);
INSERT INTO spellList (classID, spellID) VALUES (11, 225);
INSERT INTO spellList (classID, spellID) VALUES (11, 19);
INSERT INTO spellList (classID, spellID) VALUES (11, 129);
INSERT INTO spellList (classID, spellID) VALUES (11, 168);
INSERT INTO spellList (classID, spellID) VALUES (11, 224);
INSERT INTO spellList (classID, spellID) VALUES (11, 298);
INSERT INTO spellList (classID, spellID) VALUES (12, 2);
INSERT INTO spellList (classID, spellID) VALUES (12, 40);
INSERT INTO spellList (classID, spellID) VALUES (12, 71);
INSERT INTO spellList (classID, spellID) VALUES (12, 117);
INSERT INTO spellList (classID, spellID) VALUES (12, 180);
INSERT INTO spellList (classID, spellID) VALUES (12, 187);
INSERT INTO spellList (classID, spellID) VALUES (12, 201);
INSERT INTO spellList (classID, spellID) VALUES (12, 202);
INSERT INTO spellList (classID, spellID) VALUES (12, 205);
INSERT INTO spellList (classID, spellID) VALUES (12, 222);
INSERT INTO spellList (classID, spellID) VALUES (12, 227);
INSERT INTO spellList (classID, spellID) VALUES (12, 240);
INSERT INTO spellList (classID, spellID) VALUES (12, 264);
INSERT INTO spellList (classID, spellID) VALUES (12, 301);
INSERT INTO spellList (classID, spellID) VALUES (12, 4);
INSERT INTO spellList (classID, spellID) VALUES (12, 35);
INSERT INTO spellList (classID, spellID) VALUES (12, 39);
INSERT INTO spellList (classID, spellID) VALUES (12, 45);
INSERT INTO spellList (classID, spellID) VALUES (12, 49);
INSERT INTO spellList (classID, spellID) VALUES (12, 79);
INSERT INTO spellList (classID, spellID) VALUES (12, 83);
INSERT INTO spellList (classID, spellID) VALUES (12, 102);
INSERT INTO spellList (classID, spellID) VALUES (12, 107);
INSERT INTO spellList (classID, spellID) VALUES (12, 109);
INSERT INTO spellList (classID, spellID) VALUES (12, 111);
INSERT INTO spellList (classID, spellID) VALUES (12, 124);
INSERT INTO spellList (classID, spellID) VALUES (12, 126);
INSERT INTO spellList (classID, spellID) VALUES (12, 141);
INSERT INTO spellList (classID, spellID) VALUES (12, 159);
INSERT INTO spellList (classID, spellID) VALUES (12, 166);
INSERT INTO spellList (classID, spellID) VALUES (12, 167);
INSERT INTO spellList (classID, spellID) VALUES (12, 175);
INSERT INTO spellList (classID, spellID) VALUES (12, 185);
INSERT INTO spellList (classID, spellID) VALUES (12, 186);
INSERT INTO spellList (classID, spellID) VALUES (12, 190);
INSERT INTO spellList (classID, spellID) VALUES (12, 235);
INSERT INTO spellList (classID, spellID) VALUES (12, 261);
INSERT INTO spellList (classID, spellID) VALUES (12, 266);
INSERT INTO spellList (classID, spellID) VALUES (12, 268);
INSERT INTO spellList (classID, spellID) VALUES (12, 292);
INSERT INTO spellList (classID, spellID) VALUES (12, 302);
INSERT INTO spellList (classID, spellID) VALUES (12, 1);
INSERT INTO spellList (classID, spellID) VALUES (12, 5);
INSERT INTO spellList (classID, spellID) VALUES (12, 16);
INSERT INTO spellList (classID, spellID) VALUES (12, 18);
INSERT INTO spellList (classID, spellID) VALUES (12, 31);
INSERT INTO spellList (classID, spellID) VALUES (12, 33);
INSERT INTO spellList (classID, spellID) VALUES (12, 62);
INSERT INTO spellList (classID, spellID) VALUES (12, 72);
INSERT INTO spellList (classID, spellID) VALUES (12, 73);
INSERT INTO spellList (classID, spellID) VALUES (12, 81);
INSERT INTO spellList (classID, spellID) VALUES (12, 98);
INSERT INTO spellList (classID, spellID) VALUES (12, 122);
INSERT INTO spellList (classID, spellID) VALUES (12, 135);
INSERT INTO spellList (classID, spellID) VALUES (12, 148);
INSERT INTO spellList (classID, spellID) VALUES (12, 161);
INSERT INTO spellList (classID, spellID) VALUES (12, 173);
INSERT INTO spellList (classID, spellID) VALUES (12, 176);
INSERT INTO spellList (classID, spellID) VALUES (12, 179);
INSERT INTO spellList (classID, spellID) VALUES (12, 184);
INSERT INTO spellList (classID, spellID) VALUES (12, 191);
INSERT INTO spellList (classID, spellID) VALUES (12, 192);
INSERT INTO spellList (classID, spellID) VALUES (12, 207);
INSERT INTO spellList (classID, spellID) VALUES (12, 209);
INSERT INTO spellList (classID, spellID) VALUES (12, 239);
INSERT INTO spellList (classID, spellID) VALUES (12, 249);
INSERT INTO spellList (classID, spellID) VALUES (12, 252);
INSERT INTO spellList (classID, spellID) VALUES (12, 255);
INSERT INTO spellList (classID, spellID) VALUES (12, 260);
INSERT INTO spellList (classID, spellID) VALUES (12, 275);
INSERT INTO spellList (classID, spellID) VALUES (12, 283);
INSERT INTO spellList (classID, spellID) VALUES (12, 313);
INSERT INTO spellList (classID, spellID) VALUES (12, 9);
INSERT INTO spellList (classID, spellID) VALUES (12, 26);
INSERT INTO spellList (classID, spellID) VALUES (12, 32);
INSERT INTO spellList (classID, spellID) VALUES (12, 42);
INSERT INTO spellList (classID, spellID) VALUES (12, 65);
INSERT INTO spellList (classID, spellID) VALUES (12, 86);
INSERT INTO spellList (classID, spellID) VALUES (12, 108);
INSERT INTO spellList (classID, spellID) VALUES (12, 116);
INSERT INTO spellList (classID, spellID) VALUES (12, 125);
INSERT INTO spellList (classID, spellID) VALUES (12, 132);
INSERT INTO spellList (classID, spellID) VALUES (12, 139);
INSERT INTO spellList (classID, spellID) VALUES (12, 152);
INSERT INTO spellList (classID, spellID) VALUES (12, 164);
INSERT INTO spellList (classID, spellID) VALUES (12, 181);
INSERT INTO spellList (classID, spellID) VALUES (12, 188);
INSERT INTO spellList (classID, spellID) VALUES (12, 194);
INSERT INTO spellList (classID, spellID) VALUES (12, 213);
INSERT INTO spellList (classID, spellID) VALUES (12, 217);
INSERT INTO spellList (classID, spellID) VALUES (12, 234);
INSERT INTO spellList (classID, spellID) VALUES (12, 243);
INSERT INTO spellList (classID, spellID) VALUES (12, 257);
INSERT INTO spellList (classID, spellID) VALUES (12, 269);
INSERT INTO spellList (classID, spellID) VALUES (12, 270);
INSERT INTO spellList (classID, spellID) VALUES (12, 279);
INSERT INTO spellList (classID, spellID) VALUES (12, 294);
INSERT INTO spellList (classID, spellID) VALUES (12, 295);
INSERT INTO spellList (classID, spellID) VALUES (12, 303);
INSERT INTO spellList (classID, spellID) VALUES (12, 311);
INSERT INTO spellList (classID, spellID) VALUES (12, 14);
INSERT INTO spellList (classID, spellID) VALUES (12, 23);
INSERT INTO spellList (classID, spellID) VALUES (12, 27);
INSERT INTO spellList (classID, spellID) VALUES (12, 30);
INSERT INTO spellList (classID, spellID) VALUES (12, 52);
INSERT INTO spellList (classID, spellID) VALUES (12, 57);
INSERT INTO spellList (classID, spellID) VALUES (12, 63);
INSERT INTO spellList (classID, spellID) VALUES (12, 82);
INSERT INTO spellList (classID, spellID) VALUES (12, 104);
INSERT INTO spellList (classID, spellID) VALUES (12, 106);
INSERT INTO spellList (classID, spellID) VALUES (12, 118);
INSERT INTO spellList (classID, spellID) VALUES (12, 142);
INSERT INTO spellList (classID, spellID) VALUES (12, 150);
INSERT INTO spellList (classID, spellID) VALUES (12, 165);
INSERT INTO spellList (classID, spellID) VALUES (12, 183);
INSERT INTO spellList (classID, spellID) VALUES (12, 216);
INSERT INTO spellList (classID, spellID) VALUES (12, 223);
INSERT INTO spellList (classID, spellID) VALUES (12, 230);
INSERT INTO spellList (classID, spellID) VALUES (12, 244);
INSERT INTO spellList (classID, spellID) VALUES (12, 254);
INSERT INTO spellList (classID, spellID) VALUES (12, 280);
INSERT INTO spellList (classID, spellID) VALUES (12, 281);
INSERT INTO spellList (classID, spellID) VALUES (12, 305);
INSERT INTO spellList (classID, spellID) VALUES (12, 10);
INSERT INTO spellList (classID, spellID) VALUES (12, 15);
INSERT INTO spellList (classID, spellID) VALUES (12, 44);
INSERT INTO spellList (classID, spellID) VALUES (12, 51);
INSERT INTO spellList (classID, spellID) VALUES (12, 55);
INSERT INTO spellList (classID, spellID) VALUES (12, 59);
INSERT INTO spellList (classID, spellID) VALUES (12, 69);
INSERT INTO spellList (classID, spellID) VALUES (12, 92);
INSERT INTO spellList (classID, spellID) VALUES (12, 93);
INSERT INTO spellList (classID, spellID) VALUES (12, 134);
INSERT INTO spellList (classID, spellID) VALUES (12, 160);
INSERT INTO spellList (classID, spellID) VALUES (12, 177);
INSERT INTO spellList (classID, spellID) VALUES (12, 208);
INSERT INTO spellList (classID, spellID) VALUES (12, 210);
INSERT INTO spellList (classID, spellID) VALUES (12, 215);
INSERT INTO spellList (classID, spellID) VALUES (12, 219);
INSERT INTO spellList (classID, spellID) VALUES (12, 253);
INSERT INTO spellList (classID, spellID) VALUES (12, 256);
INSERT INTO spellList (classID, spellID) VALUES (12, 287);
INSERT INTO spellList (classID, spellID) VALUES (12, 288);
INSERT INTO spellList (classID, spellID) VALUES (12, 290);
INSERT INTO spellList (classID, spellID) VALUES (12, 306);
INSERT INTO spellList (classID, spellID) VALUES (12, 308);
INSERT INTO spellList (classID, spellID) VALUES (12, 38);
INSERT INTO spellList (classID, spellID) VALUES (12, 41);
INSERT INTO spellList (classID, spellID) VALUES (12, 61);
INSERT INTO spellList (classID, spellID) VALUES (12, 68);
INSERT INTO spellList (classID, spellID) VALUES (12, 84);
INSERT INTO spellList (classID, spellID) VALUES (12, 103);
INSERT INTO spellList (classID, spellID) VALUES (12, 123);
INSERT INTO spellList (classID, spellID) VALUES (12, 131);
INSERT INTO spellList (classID, spellID) VALUES (12, 138);
INSERT INTO spellList (classID, spellID) VALUES (12, 145);
INSERT INTO spellList (classID, spellID) VALUES (12, 172);
INSERT INTO spellList (classID, spellID) VALUES (12, 174);
INSERT INTO spellList (classID, spellID) VALUES (12, 189);
INSERT INTO spellList (classID, spellID) VALUES (12, 198);
INSERT INTO spellList (classID, spellID) VALUES (12, 212);
INSERT INTO spellList (classID, spellID) VALUES (12, 232);
INSERT INTO spellList (classID, spellID) VALUES (12, 284);
INSERT INTO spellList (classID, spellID) VALUES (12, 300);
INSERT INTO spellList (classID, spellID) VALUES (12, 307);
INSERT INTO spellList (classID, spellID) VALUES (12, 17);
INSERT INTO spellList (classID, spellID) VALUES (12, 76);
INSERT INTO spellList (classID, spellID) VALUES (12, 101);
INSERT INTO spellList (classID, spellID) VALUES (12, 115);
INSERT INTO spellList (classID, spellID) VALUES (12, 128);
INSERT INTO spellList (classID, spellID) VALUES (12, 193);
INSERT INTO spellList (classID, spellID) VALUES (12, 206);
INSERT INTO spellList (classID, spellID) VALUES (12, 220);
INSERT INTO spellList (classID, spellID) VALUES (12, 228);
INSERT INTO spellList (classID, spellID) VALUES (12, 233);
INSERT INTO spellList (classID, spellID) VALUES (12, 247);
INSERT INTO spellList (classID, spellID) VALUES (12, 258);
INSERT INTO spellList (classID, spellID) VALUES (12, 267);
INSERT INTO spellList (classID, spellID) VALUES (12, 286);
INSERT INTO spellList (classID, spellID) VALUES (12, 289);
INSERT INTO spellList (classID, spellID) VALUES (12, 12);
INSERT INTO spellList (classID, spellID) VALUES (12, 13);
INSERT INTO spellList (classID, spellID) VALUES (12, 43);
INSERT INTO spellList (classID, spellID) VALUES (12, 64);
INSERT INTO spellList (classID, spellID) VALUES (12, 77);
INSERT INTO spellList (classID, spellID) VALUES (12, 91);
INSERT INTO spellList (classID, spellID) VALUES (12, 110);
INSERT INTO spellList (classID, spellID) VALUES (12, 169);
INSERT INTO spellList (classID, spellID) VALUES (12, 199);
INSERT INTO spellList (classID, spellID) VALUES (12, 204);
INSERT INTO spellList (classID, spellID) VALUES (12, 225);
INSERT INTO spellList (classID, spellID) VALUES (12, 285);
INSERT INTO spellList (classID, spellID) VALUES (12, 19);
INSERT INTO spellList (classID, spellID) VALUES (12, 129);
INSERT INTO spellList (classID, spellID) VALUES (12, 133);
INSERT INTO spellList (classID, spellID) VALUES (12, 168);
INSERT INTO spellList (classID, spellID) VALUES (12, 203);
INSERT INTO spellList (classID, spellID) VALUES (12, 224);
INSERT INTO spellList (classID, spellID) VALUES (12, 229);
INSERT INTO spellList (classID, spellID) VALUES (12, 259);
INSERT INTO spellList (classID, spellID) VALUES (12, 293);
INSERT INTO spellList (classID, spellID) VALUES (12, 298);
INSERT INTO spellList (classID, spellID) VALUES (12, 314);
INSERT INTO spellList (classID, spellID) VALUES (12, 317);

INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 1, 29);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 1, 70);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 3, 178);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 3, 278);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 5, 25);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 5, 248);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 7, 75);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 7, 144);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 9, 195);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 3, 9, 238);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 3, 161);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 3, 276);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 5, 269);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 5, 270);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 7, 130);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 7, 165);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 9, 48);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Arctic', 4, 9, 51);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 3, 207);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 3, 209);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 5, 311);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 5, 312);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 7, 63);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 7, 130);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 9, 55);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Coast', 4, 9, 253);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 3, 33);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 3, 265);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 5, 66);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 5, 234);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 7, 30);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 7, 150);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 9, 171);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Desert', 4, 9, 308);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 3, 24);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 3, 275);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 5, 36);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 5, 221);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 7, 87);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 7, 130);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 9, 48);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Forest', 4, 9, 297);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 3, 173);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 3, 214);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 5, 74);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 5, 152);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 7, 87);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 7, 130);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 9, 93);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Grassland', 4, 9, 171);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 3, 275);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 3, 276);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 5, 181);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 5, 200);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 7, 280);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 7, 281);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 9, 215);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Mountain', 4, 9, 308);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 3, 1);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 3, 72);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 5, 279);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 5, 312);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 7, 130);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 7, 183);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 9, 171);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES ('Swamp', 4, 9, 253);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 3, 235);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 3, 251);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 5, 178);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 5, 319);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 9, 25);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 9, 86);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 13, 130);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 13, 144);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 17, 47);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 7, 17, 121);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 35);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 46);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 31);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 252);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 116);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 279);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 118);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 305);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 121);
INSERT INTO subclassSpellList (source, subclassID, levelAdded, spellID) VALUES (NULL, 11, 1, 149);
