INSERT INTO damageType (name) VALUES ('None');
INSERT INTO damageType (name) VALUES ('bludgeoning');
INSERT INTO damageType (name) VALUES ('piercing');
INSERT INTO damageType (name) VALUES ('slashing');

INSERT INTO weaponProperty (name, description) VALUES('Simple','Most people can use simple weapons with proficiency. These weapons include clubes, maces, and other weapons often found in the hands of commoners.');
INSERT INTO weaponProperty (name, description) VALUES('Martial','Martial weapons, including swords, axes, and polearms, require more specialized training to use effectively. Most warriors use marial weapons because these weapons put thier fighting style and training to the best use.');
INSERT INTO weaponProperty (name, description) VALUES('Ammunition','You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. Drawing the ammunition from a quiver, case, or other container is part of the attack (you need a free hand to load a one-­‐‑handed weapon).  At the end of the battle, you can recover half your expended ammunition by taking a minute to search the battlefield.  If you use a weapon that has the ammunition property to make a melee attack, you treat the weapon as an improvised weapon (see “Improvised Weapons” later in the section). A sling must be loaded to deal any damage when used in this way.');
INSERT INTO weaponProperty (name, description) VALUES('Finesse','When making an attack with a finesse weapon, you use your choice of your Strength or Dexterity modifier for the attack and damage rolls.  You must use the same modifier for both rolls.');
INSERT INTO weaponProperty (name, description) VALUES('Heavy','Small creatures have disadvantage on attack rolls with heavy weapons. A heavy weapon’s size and bulk make it too large for a Small creature to use effectively.');
INSERT INTO weaponProperty (name, description) VALUES('Light','A light weapon is small and easy to handle, making it ideal for use when fighting with two weapons.');
INSERT INTO weaponProperty (name, description) VALUES('Loading','Because of the time required to load this weapon, you can fire only one piece of ammunition from it when you use an action, bonus action, or reaction to fire it, regardless of the number of attacks you can normally make.');
INSERT INTO weaponProperty (name, description) VALUES('Range','A weapon that can be used to make a ranged attack has a range in parentheses after the ammunition or thrown property. The range lists two numbers. The first is the weapon’s normal range in feet, and the second indicates the weapon’s long range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can’t attack a target beyond the weapon’s long range.');
INSERT INTO weaponProperty (name, description) VALUES ('Reach','This weapon adds 5 feet to your reach when you attack with it, as well as when determining your reach for opportunity attacks with it.');
INSERT INTO weaponProperty (name, description) VALUES ('Thrown','If a weapon has the thrown property, you can throw the weapon to make a ranged attack. If the weapon is a melee weapon, you use the same ability modifier for that attack roll and damage roll that you would use for a melee attack with the weapon. For example, if you throw a handaxe, you use your Strength, but if you throw a dagger, you can use either your Strength or your Dexterity, since the dagger has the finesse property.');
INSERT INTO weaponProperty (name, description) VALUES ('Two-Handed','This weapon requires two hands when you attack with it.');
INSERT INTO weaponProperty (name, description) VALUES ('Versatile','This weapon can be used with one or two hands. A damage value in parentheses appears with the property—the damage when the weapon is used with two hands to make a melee attack.');
INSERT INTO weaponProperty (name, description) VALUES ('Lance','You have disadvantage when you use a lance to attack a target within 5 feet of you. Also, a lance requires two hands to wield when you aren’t mounted.');
INSERT INTO weaponProperty (name, description) VALUES ('Net','A Large or smaller creature hit by a net is restrained until it is freed. A net has no effect on creatures that are formless, or creatures that are Huge or larger. A creature can use its action to make a DC 10 Strength check, freeing itself or another creature within its reach on a success. Dealing 5 slashing damage to the net (AC 10) also frees the creature without harming it, ending the effect and destroying the net.  When you use an action, bonus action, or reaction to attack with a net, you can make only one attack regardless of the number of attacks you can normally make. ');

INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Club', 3, 1, 2, '1d4', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Dagger', 1, 2, 3, '1d4', 1);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Greatclub', 3, 2, 2, '1d8', 10);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Handaxe', 1, 5, 4, '1d6', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Javelin', 1, 5, 3, '1d6', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Light hammer', 1, 3, 2, '1d4', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Mace', 1, 5, 2, '1d6', 4);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Quarterstaff', 3, 2, 2, '1d6', 4);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Sickle', 1, 1, 4, '1d4', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Spear', 1, 1, 3, '1d6', 3);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Crossbow, light', 1, 25, 3,'1d8', 5);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Dart', 2, 5, 3, '1d4', 0.25);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Shortbow', 1, 25, 3, '1d6', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Sling', 1, 1, 2, '1d4', 0);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Battleaxe', 1, 10, 4, '1d8', 4);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Flail', 1, 10, 2, '1d8', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Glaive', 1, 20, 4, '1d10', 6);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Greataxe', 1, 30, 4, '1d12', 7);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Greatsword', 1, 50, 4, '2d6', 6);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Halberd', 1, 20, 4, '1d10', 6);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Lance', 1, 10, 3, '1d12', 6);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Longsword', 1, 15, 4, '1d8', 3);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Maul', 1, 10, 2, '2d6', 10);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Morningstar', 1, 15, 3, '1d8', 4);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Pike', 1, 5, 3, '1d10', 18);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Rapier', 1, 25, 3, '1d8', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Scimitar', 1, 25, 4, '1d6', 3);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Shortsword', 1, 10, 3, '1d6', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Trident', 1, 5, 3, '1d6', 4);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('War pick', 1, 5, 3, '1d8', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Warhammer', 1, 15, 2, '1d8', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Whip', 1, 2, 4, '1d4', 3);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Blowgun', 1, 10, 3, '1d1', 1);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Crossbow, hand', 1, 75, 3,'1d6', 3);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Crossbow, heavy', 1, 50, 3, '1d10', 18);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Longbow', 1, 50, 3, '1d8', 2);
INSERT INTO weapon (name, coinID, cost, damageTypeID, dice, weight) VALUES ('Net', 1, 1, 1, '0d0', 3);

INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (1, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (1, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (2, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (2, 4, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (2, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (2, 10, 20, 60, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (3, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (3, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (4, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (4, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (4, 10, 20, 60, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (5, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (5, 10, 30, 120, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (6, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (6, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (6, 10, 20, 60, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (7, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (8, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (8, 12, NULL, NULL, '1d8');
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (9, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (9, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (10, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (10, 10, 20, 60, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (10, 12, NULL, NULL, '1d8');
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (11, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (11, 3, 80, 320, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (11, 7, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (11, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (12, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (12, 4, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (12, 10, 20, 60, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (13, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (13, 3, 80, 320, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (13, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (14, 1, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (14, 3, 30, 120, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (15, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (15, 12, NULL, NULL, '1d10');
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (16, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (17, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (17, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (17, 9, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (17, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (18, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (18, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (18, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (19, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (19, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (19, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (20, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (20, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (20, 9, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (20, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (21, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (21, 9, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (21, 13, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (22, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (22, 12, NULL, NULL, '1d10');
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (23, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (23, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (23, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (24, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (25, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (25, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (25, 9, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (25, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (26, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (26, 4, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (27, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (27, 4, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (27, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (28, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (28, 4, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (28, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (29, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (29, 10, 20, 60, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (29, 12, NULL, NULL, '1d8');
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (30, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (31, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (31, 12, NULL, NULL, '1d10');
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (32, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (32, 4, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (32, 9, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (33, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (33, 3, 25, 100, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (33, 7, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (34, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (34, 3, 30, 120, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (34, 6, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (34, 7, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (35, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (35, 3, 100, 400, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (35, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (35, 7, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (35, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (36, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (36, 3, 150, 600, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (36, 5, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (36, 11, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (37, 2, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (37, 14, NULL, NULL, NULL);
INSERT INTO weaponWithProperty (weaponID, propertyID, lowerRange, upperRange, higherDice) VALUES (37, 10, 5, 15, NULL);
