DROP TABLE IF EXISTS planeType;
CREATE TABLE planeType (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(2500)
);

DROP TABLE IF EXISTS plane;
CREATE TABLE plane (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    planeType INTEGER REFERENCES planeType (id),
    description VARCHAR(2500)
);
