DROP TABLE IF EXISTS coin;
CREATE TABLE coin (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(15) NOT NULL,
    abbreviation VARCHAR(2) NOT NULL,
    exchangeRate DECIMAL(18,10)
);

DROP TABLE IF EXISTS armorType;
CREATE TABLE armorType (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20) NOT NULL,
    donTimeID INTEGER REFERENCES time (id),
    donTime INTEGER NOT NULL,
    doffTimeID INTEGER REFERENCES time (id),
    doffTime INTEGER NOT NULL
);

DROP TABLE IF EXISTS armor;
CREATE TABLE armor (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    typeID INTEGER REFERENCES armorType (id),
    name VARCHAR(20) NOT NULL,
    coinID INTEGER REFERENCES coin (id) NOT NULL,
    cost INTEGER NOT NULL,
    acBonus INTEGER NOT NULL,
    maxDexMod INTEGER,
    minStrength INTEGER,
    stealthPenalty BOOLEAN NOT NULL,
    weight INTEGER NOT NULL
);

DROP TABLE IF EXISTS objectAC;
CREATE TABLE objectAC (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    substance VARCHAR(15) NOT NULL,
    ac INTEGER NOT NULL
);

DROP TABLE IF EXISTS objectHP;
CREATE TABLE objectHP (
    sizeID INTEGER REFERENCES creatureSize (id) PRIMARY KEY,
    fragile VARCHAR(5) NOT NULL,
    resilient VARCHAR(5) NOT NULL
);
