DROP TABLE IF EXISTS script;
CREATE TABLE script (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR (25) NOT NULL
);

DROP TABLE IF EXISTS language;
CREATE TABLE language (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR (25) NOT NULL,
    scriptID INTEGER REFERENCES script (id),
    exotic BOOLEAN NOT NULL
);
