DROP TABLE IF EXISTS monsterType;
CREATE TABLE monsterType (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(25) NOT NULL,
    description VARCHAR(500) NOT NULL
);

DROP TABLE IF EXISTS challengeRating;
CREATE TABLE challengeRating (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cr DECIMAL NOT NULL,
    display VARCHAR(5) NOT NULL,
    xp INTEGER NOT NULL,
    proficiencyBonus INTEGER NOT NULL
);

DROP TABLE IF EXISTS movementType;
CREATE TABLE movementType (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(15) NOT NULL
);

DROP TABLE IF EXISTS sense;
CREATE TABLE sense (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20) NOT NULL
);
