CREATE TABLE monsterType (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(25) NOT NULL,
    description VARCHAR(500) NOT NULL
);

CREATE TABLE challegeRating (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cr DECIMAL NOT NULL,
    xp INTEGER NOT NULL,
    proficiencyBonus INTEGER NOT NULL
);
