DROP TABLE IF EXISTS poisonType;
CREATE TABLE poisonType (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS poison;
CREATE TABLE poison (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(25) NOT NULL,
    description VARCHAR (500) NOT NULL,
    poisonTypeID REFERENCES poisonType (id),
    coinID REFERENCES coin (id),
    price INTEGER NOT NULL
);
